from __future__ import annotations

import io
import re
import textwrap
import zipfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

from app.core.config import settings
from app.core.storage import LocalStorage, S3Storage


@dataclass(frozen=True)
class GeneratedDocument:
    storage_key: str
    url: str
    content_type: str
    output_format: str
    template: str
    size_bytes: int


_TEMPLATES: dict[str, str] = {
    "default": "# {title}\n\n{body}",
    "memo": "# Memo: {title}\n\nDate: {date}\n\n{body}\n\n---\nPrepared by Executive OS",
    "report": "# {title}\n\nGenerated: {date}\n\n## Executive Summary\n\n{body}\n\n## Notes\n\n- Draft generated by Executive OS",
    "brief": "# Brief: {title}\n\nDate: {date}\n\n{body}",
}


def _slugify(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_-]+", "-", str(value or "").strip().lower())
    cleaned = cleaned.strip("-")
    return cleaned or "document"


def _strip_markdown_inline(text_value: str) -> str:
    text_value = re.sub(r"`([^`]+)`", r"\1", text_value)
    text_value = re.sub(r"\*\*([^*]+)\*\*", r"\1", text_value)
    text_value = re.sub(r"\*([^*]+)\*", r"\1", text_value)
    text_value = re.sub(r"_([^_]+)_", r"\1", text_value)
    text_value = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1 (\2)", text_value)
    return text_value.strip()


def _markdown_to_lines(markdown: str) -> list[str]:
    out: list[str] = []
    for raw in str(markdown or "").splitlines():
        line = raw.rstrip()
        if not line.strip():
            out.append("")
            continue
        line = re.sub(r"^\s*#{1,6}\s*", "", line)
        line = re.sub(r"^\s*[-*]\s+", "- ", line)
        line = re.sub(r"^\s*\d+\.\s+", "- ", line)
        out.append(_strip_markdown_inline(line))
    while out and not out[-1]:
        out.pop()
    return out or ["(empty document)"]


def _build_pdf_bytes(lines: list[str], *, title: str) -> bytes:
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=LETTER)
    width, height = LETTER
    margin = 54
    y = height - margin
    line_height = 15

    pdf.setTitle(title)
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(margin, y, title[:120])
    y -= line_height * 2
    pdf.setFont("Helvetica", 11)

    for line in lines:
        wrapped = textwrap.wrap(line, width=95) if line else [""]
        for chunk in wrapped:
            if y <= margin:
                pdf.showPage()
                y = height - margin
                pdf.setFont("Helvetica", 11)
            pdf.drawString(margin, y, chunk)
            y -= line_height
    pdf.showPage()
    pdf.save()
    return buffer.getvalue()


def _build_docx_bytes(lines: list[str]) -> bytes:
    document_xml_parts = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">',
        "<w:body>",
    ]
    for line in lines:
        if line:
            escaped = escape(line)
            document_xml_parts.append(f"<w:p><w:r><w:t>{escaped}</w:t></w:r></w:p>")
        else:
            document_xml_parts.append("<w:p/>")
    document_xml_parts.extend(["</w:body>", "</w:document>"])
    document_xml = "".join(document_xml_parts)

    content_types_xml = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        "</Types>"
    )
    rels_xml = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
        'Target="word/document.xml"/>'
        "</Relationships>"
    )

    out = io.BytesIO()
    with zipfile.ZipFile(out, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types_xml)
        zf.writestr("_rels/.rels", rels_xml)
        zf.writestr("word/document.xml", document_xml)
    return out.getvalue()


def _render_template(
    *,
    template_name: str,
    title: str,
    body_markdown: str,
    metadata: dict[str, Any] | None,
) -> str:
    template = _TEMPLATES.get(template_name, _TEMPLATES["default"])
    values = {
        "title": title,
        "body": body_markdown.strip(),
        "date": datetime.utcnow().strftime("%Y-%m-%d"),
    }
    if metadata:
        for key, value in metadata.items():
            if key not in values:
                values[key] = str(value)
    return template.format(**values).strip()


def _document_storage():
    backend = str(settings.STORAGE_BACKEND or "local").strip().lower()
    if backend == "s3":
        bucket = str(settings.S3_DOCUMENTS_BUCKET or settings.S3_BUCKET or "").strip()
        if not bucket:
            raise RuntimeError("S3_DOCUMENTS_BUCKET or S3_BUCKET must be configured for S3 storage")
        return S3Storage(
            bucket=bucket,
            region=settings.S3_REGION or settings.AWS_REGION,
            endpoint_url=settings.S3_ENDPOINT_URL,
        )

    base = Path(settings.LOCAL_STORAGE_PATH or "./storage")
    return LocalStorage(base_path=base)


def _build_storage_key(*, user_id: str, title: str, output_format: str) -> str:
    timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    slug = _slugify(title)
    return f"{user_id}/documents/{timestamp}_{slug}.{output_format}"


def generate_document(
    *,
    user_id: str,
    title: str,
    markdown: str,
    output_format: str = "pdf",
    template: str = "default",
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    fmt = str(output_format or "pdf").strip().lower()
    if fmt not in {"pdf", "docx"}:
        raise ValueError("output_format must be one of: pdf, docx")

    safe_title = str(title or "").strip() or "Generated Document"
    rendered = _render_template(
        template_name=str(template or "default").strip().lower(),
        title=safe_title,
        body_markdown=str(markdown or "").strip(),
        metadata=metadata,
    )
    lines = _markdown_to_lines(rendered)

    if fmt == "pdf":
        payload = _build_pdf_bytes(lines, title=safe_title)
        content_type = "application/pdf"
    else:
        payload = _build_docx_bytes(lines)
        content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

    storage = _document_storage()
    key = _build_storage_key(user_id=user_id, title=safe_title, output_format=fmt)
    storage_key = storage.put_bytes(key, payload, content_type=content_type)
    url = storage.get_url(storage_key, expires_seconds=3600)

    generated = GeneratedDocument(
        storage_key=storage_key,
        url=url,
        content_type=content_type,
        output_format=fmt,
        template=str(template or "default").strip().lower() or "default",
        size_bytes=len(payload),
    )
    return {
        "storage_key": generated.storage_key,
        "url": generated.url,
        "content_type": generated.content_type,
        "output_format": generated.output_format,
        "template": generated.template,
        "size_bytes": generated.size_bytes,
    }
