# backend/app/services/smart_home/providers/base.py

from __future__ import annotations

from typing import Protocol, Any


class SmartHomeProvider(Protocol):
    def discover_devices(self, user_id: str) -> list[dict]: ...
    def execute_command(self, user_id: str, device: dict, command: str, params: dict | None = None) -> dict: ...
    def list_scenes(self, user_id: str) -> list[dict]: ...
    def activate_scene(self, user_id: str, scene_id: str) -> dict: ...
    def read_energy(self, user_id: str, entity_ids: list[str]) -> list[dict]: ...

