"""add voice_calls table

Revision ID: ab97ac091deb
Revises: 7acebebdb2cb
Create Date: 2026-02-06 16:40:03.503680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab97ac091deb'
down_revision: Union[str, Sequence[str], None] = '7acebebdb2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spending_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('limit_amount', sa.Float(), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('max_transaction_amount', sa.Float(), nullable=True),
    sa.Column('max_transactions_per_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spending_limits_created_at'), 'spending_limits', ['created_at'], unique=False)
    op.create_index(op.f('ix_spending_limits_period'), 'spending_limits', ['period'], unique=False)
    op.create_index(op.f('ix_spending_limits_user_id'), 'spending_limits', ['user_id'], unique=False)
    op.create_table('voice_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('voice_profile', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items_json', sa.Text(), nullable=True),
    sa.Column('call_sid', sa.String(), nullable=True),
    sa.Column('stream_sid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_calls_call_sid'), 'voice_calls', ['call_sid'], unique=False)
    op.create_index(op.f('ix_voice_calls_created_at'), 'voice_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_voice_calls_direction'), 'voice_calls', ['direction'], unique=False)
    op.create_index(op.f('ix_voice_calls_from_number'), 'voice_calls', ['from_number'], unique=False)
    op.create_index(op.f('ix_voice_calls_purpose'), 'voice_calls', ['purpose'], unique=False)
    op.create_index(op.f('ix_voice_calls_status'), 'voice_calls', ['status'], unique=False)
    op.create_index(op.f('ix_voice_calls_stream_sid'), 'voice_calls', ['stream_sid'], unique=False)
    op.create_index(op.f('ix_voice_calls_to_number'), 'voice_calls', ['to_number'], unique=False)
    op.create_index(op.f('ix_voice_calls_user_id'), 'voice_calls', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('booking_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confirmation_number', sa.String(), nullable=True),
    sa.Column('provider_booking_id', sa.String(), nullable=True),
    sa.Column('pnr', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_type'), 'bookings', ['booking_type'], unique=False)
    op.create_index(op.f('ix_bookings_confirmation_number'), 'bookings', ['confirmation_number'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_pnr'), 'bookings', ['pnr'], unique=False)
    op.create_index(op.f('ix_bookings_proposal_id'), 'bookings', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_bookings_provider'), 'bookings', ['provider'], unique=False)
    op.create_index(op.f('ix_bookings_provider_booking_id'), 'bookings', ['provider_booking_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_transaction_id'), 'bookings', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_created_at'), 'execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_logs_proposal_id'), 'execution_logs', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_execution_logs_status'), 'execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_execution_logs_step'), 'execution_logs', ['step'], unique=False)
    op.create_index(op.f('ix_execution_logs_transaction_id'), 'execution_logs', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_proposals_created_at'), 'proposals', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_created_at'), table_name='proposals')
    op.drop_index(op.f('ix_execution_logs_transaction_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_step'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_status'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_proposal_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_created_at'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_transaction_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider_booking_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_proposal_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pnr'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_confirmation_number'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_type'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_voice_calls_user_id'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_to_number'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_stream_sid'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_status'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_purpose'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_from_number'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_direction'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_created_at'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_call_sid'), table_name='voice_calls')
    op.drop_table('voice_calls')
    op.drop_index(op.f('ix_spending_limits_user_id'), table_name='spending_limits')
    op.drop_index(op.f('ix_spending_limits_period'), table_name='spending_limits')
    op.drop_index(op.f('ix_spending_limits_created_at'), table_name='spending_limits')
    op.drop_table('spending_limits')
    # ### end Alembic commands ###
