// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/executor/v1/executor.proto

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchToolRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ToolKey        string                 `protobuf:"bytes,3,opt,name=tool_key,json=toolKey,proto3" json:"tool_key,omitempty"`
	ReceiptId      string                 `protobuf:"bytes,4,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	InputJson      string                 `protobuf:"bytes,6,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	OauthToken     string                 `protobuf:"bytes,7,opt,name=oauth_token,json=oauthToken,proto3" json:"oauth_token,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchToolRequest) Reset() {
	*x = DispatchToolRequest{}
	mi := &file_proto_executor_v1_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchToolRequest) ProtoMessage() {}

func (x *DispatchToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v1_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchToolRequest.ProtoReflect.Descriptor instead.
func (*DispatchToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchToolRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DispatchToolRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DispatchToolRequest) GetToolKey() string {
	if x != nil {
		return x.ToolKey
	}
	return ""
}

func (x *DispatchToolRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *DispatchToolRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *DispatchToolRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *DispatchToolRequest) GetOauthToken() string {
	if x != nil {
		return x.OauthToken
	}
	return ""
}

func (x *DispatchToolRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type DispatchToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ToolKey       string                 `protobuf:"bytes,2,opt,name=tool_key,json=toolKey,proto3" json:"tool_key,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	PayloadHash   string                 `protobuf:"bytes,5,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	OutputJson    string                 `protobuf:"bytes,6,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchToolResponse) Reset() {
	*x = DispatchToolResponse{}
	mi := &file_proto_executor_v1_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchToolResponse) ProtoMessage() {}

func (x *DispatchToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v1_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchToolResponse.ProtoReflect.Descriptor instead.
func (*DispatchToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v1_executor_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchToolResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *DispatchToolResponse) GetToolKey() string {
	if x != nil {
		return x.ToolKey
	}
	return ""
}

func (x *DispatchToolResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DispatchToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchToolResponse) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

func (x *DispatchToolResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *DispatchToolResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DispatchToolResponse) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *DispatchToolResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_proto_executor_v1_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v1_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_proto_executor_v1_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ExecutionEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusRequest) Reset() {
	*x = GetExecutionStatusRequest{}
	mi := &file_proto_executor_v1_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusRequest) ProtoMessage() {}

func (x *GetExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v1_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v1_executor_proto_rawDescGZIP(), []int{3}
}

func (x *GetExecutionStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetExecutionStatusRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type GetExecutionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OutputJson    string                 `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusResponse) Reset() {
	*x = GetExecutionStatusResponse{}
	mi := &file_proto_executor_v1_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusResponse) ProtoMessage() {}

func (x *GetExecutionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v1_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v1_executor_proto_rawDescGZIP(), []int{4}
}

func (x *GetExecutionStatusResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_executor_v1_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v1_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v1_executor_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_executor_v1_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v1_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v1_executor_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_executor_v1_executor_proto protoreflect.FileDescriptor

const file_proto_executor_v1_executor_proto_rawDesc = "" +
	"\n" +
	" proto/executor/v1/executor.proto\x12\vexecutor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\x13DispatchToolRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\btool_key\x18\x03 \x01(\tR\atoolKey\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x04 \x01(\tR\treceiptId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"input_json\x18\x06 \x01(\tR\tinputJson\x12\x1f\n" +
	"\voauth_token\x18\a \x01(\tR\n" +
	"oauthToken\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\"\xc9\x02\n" +
	"\x14DispatchToolResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\btool_key\x18\x02 \x01(\tR\atoolKey\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12!\n" +
	"\fpayload_hash\x18\x05 \x01(\tR\vpayloadHash\x12\x1f\n" +
	"\voutput_json\x18\x06 \x01(\tR\n" +
	"outputJson\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12;\n" +
	"\vexecuted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x03R\tlatencyMs\"\xc0\x01\n" +
	"\x0eExecutionEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"a\n" +
	"\x19GetExecutionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\"\xb7\x01\n" +
	"\x1aGetExecutionStatusResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\tR\n" +
	"outputJson\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xf6\x02\n" +
	"\x0fExecutorService\x12S\n" +
	"\fDispatchTool\x12 .executor.v1.DispatchToolRequest\x1a!.executor.v1.DispatchToolResponse\x12U\n" +
	"\x12DispatchToolStream\x12 .executor.v1.DispatchToolRequest\x1a\x1b.executor.v1.ExecutionEvent0\x01\x12e\n" +
	"\x12GetExecutionStatus\x12&.executor.v1.GetExecutionStatusRequest\x1a'.executor.v1.GetExecutionStatusResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.executor.v1.HealthCheckRequest\x1a .executor.v1.HealthCheckResponseB7Z5github.com/brevio/brevio/proto/executor/v1;executorv1b\x06proto3"

var (
	file_proto_executor_v1_executor_proto_rawDescOnce sync.Once
	file_proto_executor_v1_executor_proto_rawDescData []byte
)

func file_proto_executor_v1_executor_proto_rawDescGZIP() []byte {
	file_proto_executor_v1_executor_proto_rawDescOnce.Do(func() {
		file_proto_executor_v1_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executor_v1_executor_proto_rawDesc), len(file_proto_executor_v1_executor_proto_rawDesc)))
	})
	return file_proto_executor_v1_executor_proto_rawDescData
}

var file_proto_executor_v1_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_executor_v1_executor_proto_goTypes = []any{
	(*DispatchToolRequest)(nil),        // 0: executor.v1.DispatchToolRequest
	(*DispatchToolResponse)(nil),       // 1: executor.v1.DispatchToolResponse
	(*ExecutionEvent)(nil),             // 2: executor.v1.ExecutionEvent
	(*GetExecutionStatusRequest)(nil),  // 3: executor.v1.GetExecutionStatusRequest
	(*GetExecutionStatusResponse)(nil), // 4: executor.v1.GetExecutionStatusResponse
	(*HealthCheckRequest)(nil),         // 5: executor.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 6: executor.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_proto_executor_v1_executor_proto_depIdxs = []int32{
	7, // 0: executor.v1.DispatchToolResponse.executed_at:type_name -> google.protobuf.Timestamp
	7, // 1: executor.v1.ExecutionEvent.timestamp:type_name -> google.protobuf.Timestamp
	7, // 2: executor.v1.GetExecutionStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	0, // 3: executor.v1.ExecutorService.DispatchTool:input_type -> executor.v1.DispatchToolRequest
	0, // 4: executor.v1.ExecutorService.DispatchToolStream:input_type -> executor.v1.DispatchToolRequest
	3, // 5: executor.v1.ExecutorService.GetExecutionStatus:input_type -> executor.v1.GetExecutionStatusRequest
	5, // 6: executor.v1.ExecutorService.HealthCheck:input_type -> executor.v1.HealthCheckRequest
	1, // 7: executor.v1.ExecutorService.DispatchTool:output_type -> executor.v1.DispatchToolResponse
	2, // 8: executor.v1.ExecutorService.DispatchToolStream:output_type -> executor.v1.ExecutionEvent
	4, // 9: executor.v1.ExecutorService.GetExecutionStatus:output_type -> executor.v1.GetExecutionStatusResponse
	6, // 10: executor.v1.ExecutorService.HealthCheck:output_type -> executor.v1.HealthCheckResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_executor_v1_executor_proto_init() }
func file_proto_executor_v1_executor_proto_init() {
	if File_proto_executor_v1_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executor_v1_executor_proto_rawDesc), len(file_proto_executor_v1_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_executor_v1_executor_proto_goTypes,
		DependencyIndexes: file_proto_executor_v1_executor_proto_depIdxs,
		MessageInfos:      file_proto_executor_v1_executor_proto_msgTypes,
	}.Build()
	File_proto_executor_v1_executor_proto = out.File
	file_proto_executor_v1_executor_proto_goTypes = nil
	file_proto_executor_v1_executor_proto_depIdxs = nil
}
