package brain

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/brevio/brevio/internal/cognition"
	"github.com/brevio/brevio/internal/llm"
)

var (
	ErrReasoningTimeout    = errors.New("reasoning: loop timed out")
	ErrReasoningNoContext  = errors.New("reasoning: no context provided")
	ErrReasoningMaxRetries = errors.New("reasoning: max iterations reached without satisfactory quality")
	ErrPlanEmpty           = errors.New("reasoning: planner produced empty plan")
	ErrExecutorNoPlan      = errors.New("reasoning: executor received nil plan")
)

// Message represents a single conversation message.
type Message struct {
	Role      string         `json:"role"`    // "user", "assistant", "system"
	Content   string         `json:"content"`
	Timestamp int64          `json:"timestamp"`
	Metadata  map[string]any `json:"metadata,omitempty"`
}

// CompressConversation returns a compacted conversation history.
// Keeps the last keepTurns messages verbatim. Summarizes everything before that
// using the provided Summarizer, prepending the result as a synthetic system message.
func CompressConversation(
	ctx context.Context,
	history []Message,
	contextBudgetTokens int,
	keepTurns int,
	summarizer Summarizer,
) ([]Message, error) {
	if len(history) == 0 || summarizer == nil || contextBudgetTokens <= 0 {
		return history, nil
	}

	// Conservative token estimate: ~4 chars per token + 50 overhead per message.
	estimated := 0
	for _, m := range history {
		estimated += len(m.Content)/4 + 50
	}
	threshold := int(float64(contextBudgetTokens) * 0.70)
	if estimated <= threshold {
		return history, nil
	}
	if keepTurns <= 0 {
		keepTurns = 6
	}
	if len(history) <= keepTurns {
		return history, nil
	}

	cutpoint := len(history) - keepTurns
	older := history[:cutpoint]
	recent := history[cutpoint:]

	// Serialize older messages to text for the summarizer.
	var sb strings.Builder
	for _, m := range older {
		sb.WriteString(m.Role)
		sb.WriteString(": ")
		sb.WriteString(m.Content)
		sb.WriteString("\n")
	}
	summary, err := summarizer.SummarizeText(ctx, sb.String(), 256)
	if err != nil {
		return history, fmt.Errorf("compress: summarize failed (using full history): %w", err)
	}

	compressed := make([]Message, 0, 1+len(recent))
	compressed = append(compressed, Message{
		Role:      "system",
		Content:   "[Earlier conversation summary: " + summary + "]",
		Timestamp: time.Now().Unix(),
		Metadata:  map[string]any{"compressed": true, "summarized_turns": cutpoint},
	})
	compressed = append(compressed, recent...)
	return compressed, nil
}

// ReasoningContext carries all context needed for a reasoning loop iteration.
type ReasoningContext struct {
	MessageID           string    `json:"message_id"`
	WorkspaceID         string    `json:"workspace_id"`
	UserID              string    `json:"user_id,omitempty"`
	Intent              string    `json:"intent"`
	Confidence          float64   `json:"confidence"`
	ConversationHistory []Message `json:"conversation_history"`
	ContextBudget       int       `json:"context_budget"` // max tokens to use
	MemoryContext       string    `json:"memory_context,omitempty"`
	RAGContext          string    `json:"rag_context,omitempty"`
	RetryHints          string    `json:"retry_hints,omitempty"`
	OriginalPayload     string    `json:"original_payload,omitempty"`

	// RetrievedFacts holds RAG results injected before planning.
	RetrievedFacts []RetrievedFact `json:"retrieved_facts,omitempty"`

	// StepBackGoal is the abstract goal from the Step-Back pre-pass.
	StepBackGoal string `json:"step_back_goal,omitempty"`

	// WorkspaceQualityTarget overrides qualityTarget when > 0.
	WorkspaceQualityTarget float64 `json:"workspace_quality_target,omitempty"`
}

// RetrievedFact is a single RAG result injected into the planning context.
type RetrievedFact struct {
	ChunkID   string  `json:"chunk_id"`
	Score     float64 `json:"score"`
	Snippet   string  `json:"snippet"`
	Source    string  `json:"source"`
	DataClass string  `json:"data_class,omitempty"`
}

// formatRetrievedFacts serialises retrieved facts for injection into planner context.
func formatRetrievedFacts(facts []RetrievedFact) string {
	if len(facts) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\n\n## Relevant context from memory\n")
	limit := 8
	if len(facts) < limit {
		limit = len(facts)
	}
	for _, f := range facts[:limit] {
		b.WriteString(fmt.Sprintf("- [%s score=%.2f] %s\n", f.Source, f.Score, f.Snippet))
	}
	return b.String()
}

// PlanStep represents a single step in an execution plan.
type PlanStep struct {
	ToolKey    string         `json:"tool_key"`
	Parameters map[string]any `json:"parameters"`
	DependsOn  []int          `json:"depends_on,omitempty"` // indices of steps this depends on
	Phase      string         `json:"phase"`                // "gather", "act", "verify"
}

// Plan represents a complete execution plan generated by the planner.
type Plan struct {
	WorkspaceID     string     `json:"workspace_id,omitempty"`
	Steps           []PlanStep `json:"steps"`
	RiskLevel       string     `json:"risk_level"` // "low", "elevated", "critical"
	EstimatedTokens int        `json:"estimated_tokens"`
}

// StepResult captures the outcome of executing a single plan step.
type StepResult struct {
	StepIndex int            `json:"step_index"`
	ToolKey   string         `json:"tool_key"`
	Success   bool           `json:"success"`
	Output    map[string]any `json:"output,omitempty"`
	Error     string         `json:"error,omitempty"`
}

// ExecutionResult captures the outcomes of all plan steps.
type ExecutionResult struct {
	Results            []StepResult `json:"results"`
	CompensationNeeded bool         `json:"compensation_needed"`
}

// CriticAssessment evaluates the quality of an execution.
// StepVerdict carries the per-step semantic evaluation from the PRM critic.
type StepVerdict struct {
	StepIndex   int    `json:"step_index"`
	ToolKey     string `json:"tool_key"`
	Verdict     string `json:"verdict"`                // "pass" | "fail" | "uncertain"
	Explanation string `json:"explanation"`
	RetryHint   string `json:"retry_hint,omitempty"`
}

type CriticAssessment struct {
	QualityScore    float64       `json:"quality_score"` // 0.0 to 1.0
	Issues          []string      `json:"issues,omitempty"`
	ShouldRetry     bool          `json:"should_retry"`
	RetryHints      []string      `json:"retry_hints,omitempty"`
	SemanticVerdict string        `json:"semantic_verdict,omitempty"` // "pass"|"fail"|"heuristic"
	StepVerdicts    []StepVerdict `json:"step_verdicts,omitempty"`
	FailedStepKeys  []string      `json:"failed_step_keys,omitempty"`
}

// ReflectionResult captures lessons from a reasoning iteration.
type ReflectionResult struct {
	Lessons                []string `json:"lessons,omitempty"`
	ConfidenceAdjustment   float64  `json:"confidence_adjustment"` // delta to apply
	SuggestedImprovements  []string `json:"suggested_improvements,omitempty"`
}

// LoopResult is the final output of a complete reasoning loop.
type LoopResult struct {
	FinalPlan     *Plan            `json:"final_plan"`
	FinalResult   *ExecutionResult `json:"final_result"`
	Iterations    int              `json:"iterations"`
	CriticScore   float64          `json:"critic_score"`
	Lessons       []string         `json:"lessons,omitempty"`
	DynamicBudget int              `json:"dynamic_budget,omitempty"`
}

// Summarizer compresses a conversation text into a brief summary string.
// Defined here (not in internal/llm) to avoid circular imports.
// brain serializes []Message to text before calling this interface.
type Summarizer interface {
	SummarizeText(ctx context.Context, conversationText string, maxOutputTokens int) (string, error)
}

// CouncilConvener gates critical actions via multi-agent deliberation.
type CouncilConvener interface {
	ConveneAndDecide(ctx context.Context, workspaceID, topic, actionDesc string) (bool, error)
}

// ToolExecutor is the interface for executing tool calls.
type ToolExecutor interface {
	Execute(ctx context.Context, toolKey string, params map[string]any) (map[string]any, error)
}

// ReasoningLoop orchestrates the PLANNER -> EXECUTOR -> CRITIC -> REFLECTOR cycle.
type ReasoningLoop struct {
	executor       ToolExecutor
	qualityTarget  float64       // critic score threshold to stop iterating (default 0.8)
	maxIterations  int           // safety cap (default 3)
	stepTimeout    time.Duration // timeout per individual step
	intelligence   *llm.IntelligenceService
	gotEngine      *cognition.GoTEngine
	gotThreshold   float64
	gotBranches    int
	worldModel       *WorldModelService
	decomposition     *DynamicDecompositionService
	maxIterationsCap  int
	moaCfg                 llm.MoAConfig
	summarizer             Summarizer
	compressThreshold      float64
	llmClient              llm.Client
	registeredTools        []llm.ToolDefinition
	enableExtendedThinking bool
	thinkingBudgetTokens   int
	selfConsistencyK       int
	semanticCritic         *SemanticCriticService
	prm                    *ProcessRewardModel
	gotLLMEngine           *cognition.GoTLLMEngine
	mctsConfig             *MCTSConfig
	councilSvc             CouncilConvener
}

// ReasoningLoopConfig holds configuration for a ReasoningLoop.
type ReasoningLoopConfig struct {
	Executor         ToolExecutor
	QualityTarget    float64
	MaxIterations    int
	MaxIterationsCap int
	StepTimeout      time.Duration
	Intelligence     *llm.IntelligenceService
	GoTEngine        *cognition.GoTEngine
	GoTThreshold     float64 // confidence below this triggers GoT (default 0.75)
	GoTBranches      int     // alternative hypotheses to generate (default 3, max 5)
	WorldModel       *WorldModelService // nil = skip world fact enrichment
	Decomposition    *DynamicDecompositionService
	MoA               llm.MoAConfig // zero value = disabled
	Summarizer        Summarizer     // optional; if nil, compression is skipped gracefully
	CompressThreshold float64        // fraction of ContextBudget at which to compress (default 0.70)

	// LLMClient drives LLM-based planning. nil = heuristic fallback.
	LLMClient llm.Client
	// RegisteredTools is the tool registry the planner may select from.
	RegisteredTools []llm.ToolDefinition
	// EnableExtendedThinking activates Anthropic extended thinking on planner calls.
	EnableExtendedThinking bool
	// ThinkingBudgetTokens is the extended thinking budget (default 8192).
	ThinkingBudgetTokens int
	// SelfConsistencyK is the number of plan samples for majority voting. 0 or 1 = single sample.
	SelfConsistencyK int
	// SemanticCritic replaces heuristic critic when set.
	SemanticCritic *SemanticCriticService
	// PRM scores each step after execution; nil or Enabled=false = disabled.
	PRM *ProcessRewardModel
	// GoTLLMEngine runs Graph-of-Thought reasoning on complex multi-intent requests.
	GoTLLMEngine *cognition.GoTLLMEngine
	// MCTSConfig enables MCTS plan exploration for critical-risk plans.
	MCTSConfig *MCTSConfig
	// CouncilSvc gates critical actions via multi-agent deliberation.
	CouncilSvc CouncilConvener
}

// NewReasoningLoop creates a new ReasoningLoop with the given config.
func NewReasoningLoop(cfg ReasoningLoopConfig) *ReasoningLoop {
	qualityTarget := cfg.QualityTarget
	if qualityTarget <= 0 || qualityTarget > 1.0 {
		qualityTarget = 0.8
	}
	maxIter := cfg.MaxIterations
	if maxIter <= 0 {
		maxIter = 3
	}
	if cfg.MaxIterationsCap > 0 && maxIter > cfg.MaxIterationsCap {
		maxIter = cfg.MaxIterationsCap
	}
	stepTimeout := cfg.StepTimeout
	if stepTimeout <= 0 {
		stepTimeout = 30 * time.Second
	}
	gotThreshold := cfg.GoTThreshold
	if gotThreshold <= 0 {
		gotThreshold = 0.75
	}
	gotBranches := cfg.GoTBranches
	if gotBranches <= 0 {
		gotBranches = 3
	}
	if gotBranches > 5 {
		gotBranches = 5
	}
	iterCap := cfg.MaxIterationsCap
	if iterCap <= 0 {
		iterCap = 8
	}
	compressThreshold := cfg.CompressThreshold
	if compressThreshold <= 0 || compressThreshold > 1.0 {
		compressThreshold = 0.70
	}
	thinkingBudget := cfg.ThinkingBudgetTokens
	if thinkingBudget <= 0 {
		thinkingBudget = 8192
	}
	scK := cfg.SelfConsistencyK
	if scK <= 0 {
		scK = 1
	}
	return &ReasoningLoop{
		executor:               cfg.Executor,
		qualityTarget:          qualityTarget,
		maxIterations:          maxIter,
		stepTimeout:            stepTimeout,
		intelligence:           cfg.Intelligence,
		gotEngine:              cfg.GoTEngine,
		gotThreshold:           gotThreshold,
		gotBranches:            gotBranches,
		worldModel:             cfg.WorldModel,
		decomposition:          cfg.Decomposition,
		maxIterationsCap:       iterCap,
		moaCfg:                 cfg.MoA,
		summarizer:             cfg.Summarizer,
		compressThreshold:      compressThreshold,
		llmClient:              cfg.LLMClient,
		registeredTools:        cfg.RegisteredTools,
		enableExtendedThinking: cfg.EnableExtendedThinking,
		thinkingBudgetTokens:   thinkingBudget,
		selfConsistencyK:       scK,
		semanticCritic:         cfg.SemanticCritic,
		prm:                    cfg.PRM,
		gotLLMEngine:           cfg.GoTLLMEngine,
		mctsConfig:             cfg.MCTSConfig,
		councilSvc:             cfg.CouncilSvc,
	}
}

// PlannerStep generates an execution plan based on the reasoning context.
// It analyzes the intent and conversation history to determine what tools
// to invoke and in what order.
func (rl *ReasoningLoop) PlannerStep(ctx context.Context, rc *ReasoningContext) (*Plan, error) {
	if rc == nil {
		return nil, ErrReasoningNoContext
	}
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("reasoning: planner cancelled: %w", err)
	}

	intent := strings.TrimSpace(rc.Intent)
	if intent == "" {
		return nil, fmt.Errorf("%w: empty intent", ErrPlanEmpty)
	}

	// GoT pre-pass: for complex multi-intent requests, run GoT reasoning.
	if rl.gotLLMEngine != nil && rc != nil {
		gotNeeded := len(strings.Fields(rc.Intent)) > 50 && strings.Count(rc.Intent, " and ") >= 2
		if gotNeeded {
			gotResult, gotErr := rl.gotLLMEngine.Run(ctx, cognition.GoTRunRequest{
				WorkspaceID: rc.WorkspaceID,
				Question:    rc.Intent,
				Context:     formatRetrievedFacts(rc.RetrievedFacts),
				MaxSteps:    2,
			})
			if gotErr == nil && gotResult != nil && gotResult.Confidence >= 0.5 {
				if rc.StepBackGoal == "" {
					rc.StepBackGoal = gotResult.Conclusion
				} else {
					rc.StepBackGoal = rc.StepBackGoal + "; GoT: " + gotResult.Conclusion
				}
			}
		}
	}

	// LLM-driven planner path (PROMPT_03: tool calling + self-consistency).
	if rl.llmClient != nil {
		input := LLMPlannerInput{
			WorkspaceID:    rc.WorkspaceID,
			Intent:         intent,
			StepBackGoal:   rc.StepBackGoal,
			RetrievedFacts: rc.RetrievedFacts,
			Tools:          rl.registeredTools,
			ContextBudget:  rc.ContextBudget,
			UseThinking:    rl.enableExtendedThinking,
			ThinkingBudget: rl.thinkingBudgetTokens,
		}

		// MCTS path: for critical plans when MCTSConfig is set.
		if rl.mctsConfig != nil {
			quickPlan, _, qErr := callLLMPlanner(ctx, rl.llmClient, input)
			if qErr == nil && quickPlan != nil && quickPlan.RiskLevel == "critical" {
				mcts := NewMCTSPlanner(*rl.mctsConfig)
				mcts.cfg.LLMClient = rl.llmClient
				if mctsPlan, mctsErr := mcts.Search(ctx, input); mctsErr == nil && mctsPlan != nil {
					return mctsPlan, nil
				}
			} else if qErr == nil && quickPlan != nil {
				return quickPlan, nil
			}
		}

		// For critical plans, use self-consistency sampling.
		if rl.selfConsistencyK > 1 {
			quickPlan, _, quickErr := callLLMPlanner(ctx, rl.llmClient, input)
			if quickErr == nil && quickPlan != nil && quickPlan.RiskLevel == "critical" {
				sc := NewSelfConsistencyPlanner(rl.llmClient, rl.selfConsistencyK)
				plan, err := sc.SelectPlan(ctx, input)
				if err == nil && plan != nil {
					return plan, nil
				}
			} else if quickErr == nil && quickPlan != nil {
				return quickPlan, nil
			}
		}

		plan, _, err := callLLMPlanner(ctx, rl.llmClient, input)
		if err == nil && plan != nil && len(plan.Steps) > 0 {
			return plan, nil
		}
		// LLM planner failed — fall through to intelligence service or heuristic.
	}

	// Prepend RetryHints so the LLM sees what failed in previous iterations.
	memCtx := rc.MemoryContext
	if rc.RetryHints != "" {
		memCtx = "RETRY CONTEXT (previous attempt failures):\n" + rc.RetryHints + "\n\n" + memCtx
	}

	// GoT multi-path planning: activate when confidence is low.
	if rl.gotEngine != nil && rl.intelligence != nil && rc.Confidence < rl.gotThreshold {
		plan, gotErr := rl.planWithGoT(ctx, rc, memCtx)
		if gotErr == nil && plan != nil {
			return plan, nil
		}
	}

	// MoA path: activate for critical-risk or low confidence.
	if rl.intelligence != nil && rl.moaCfg.Enabled &&
		(rc.Confidence < 0.7 || strings.Contains(strings.ToLower(intent), "critical")) {
		genPlan, _, err := rl.intelligence.GeneratePlanMoA(
			ctx, intent, rc.Confidence,
			rc.OriginalPayload, memCtx, rc.RAGContext, rl.moaCfg,
		)
		if err == nil && genPlan != nil && len(genPlan.Actions) > 0 {
			return generatedPlanToBrainPlan(genPlan, rc.WorkspaceID), nil
		}
	}

	// Intelligence service path.
	if rl.intelligence != nil {
		genPlan, _, err := rl.intelligence.GeneratePlan(
			ctx, intent, rc.Confidence, rc.OriginalPayload, memCtx, rc.RAGContext,
		)
		if err == nil && genPlan != nil && len(genPlan.Actions) > 0 {
			return generatedPlanToBrainPlan(genPlan, rc.WorkspaceID), nil
		}
	}

	// Heuristic fallback (test mode / nil client).
	steps := buildStepsForIntentFallback(intent, rc)
	if len(steps) == 0 {
		return nil, fmt.Errorf("%w: could not derive steps for intent %q", ErrPlanEmpty, rc.Intent)
	}
	return &Plan{
		WorkspaceID:     rc.WorkspaceID,
		Steps:           steps,
		RiskLevel:       assessRiskLevel(steps),
		EstimatedTokens: estimateTokens(steps, rc.ContextBudget),
	}, nil
}

// buildStepsForIntentFallback is the heuristic keyword-based fallback planner.
// Only used when IntelligenceService is unavailable or returns an error.
func buildStepsForIntentFallback(intent string, rc *ReasoningContext) []PlanStep {
	intent = strings.ToLower(intent)
	var steps []PlanStep

	// Phase 1: Gather context
	if containsAny(intent, "email", "mail", "message") {
		steps = append(steps, PlanStep{
			ToolKey:    "email_read",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "query": rc.Intent},
			Phase:      "gather",
		})
	}
	if containsAny(intent, "calendar", "meeting", "schedule", "event") {
		steps = append(steps, PlanStep{
			ToolKey:    "calendar_read",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "query": rc.Intent},
			Phase:      "gather",
		})
	}
	if containsAny(intent, "document", "file", "doc", "note") {
		steps = append(steps, PlanStep{
			ToolKey:    "document_read",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "query": rc.Intent},
			Phase:      "gather",
		})
	}
	if containsAny(intent, "search", "find", "look up", "web") {
		steps = append(steps, PlanStep{
			ToolKey:    "web_search",
			Parameters: map[string]any{"query": rc.Intent},
			Phase:      "gather",
		})
	}

	// Phase 2: Act
	if containsAny(intent, "send", "reply", "forward") {
		gatherIdx := -1
		for i, s := range steps {
			if s.Phase == "gather" {
				gatherIdx = i
			}
		}
		step := PlanStep{
			ToolKey:    "email_send",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "intent": rc.Intent},
			Phase:      "act",
		}
		if gatherIdx >= 0 {
			step.DependsOn = []int{gatherIdx}
		}
		steps = append(steps, step)
	}
	if containsAny(intent, "create event", "schedule meeting", "book", "set up meeting") {
		step := PlanStep{
			ToolKey:    "calendar_write",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "intent": rc.Intent},
			Phase:      "act",
		}
		steps = append(steps, step)
	}

	// Phase 3: Verify — add a verification step if any act step exists
	hasAct := false
	for _, s := range steps {
		if s.Phase == "act" {
			hasAct = true
			break
		}
	}
	if hasAct {
		actIndices := make([]int, 0)
		for i, s := range steps {
			if s.Phase == "act" {
				actIndices = append(actIndices, i)
			}
		}
		steps = append(steps, PlanStep{
			ToolKey:    "verify_output",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID},
			DependsOn:  actIndices,
			Phase:      "verify",
		})
	}

	return steps
}

// generatedPlanToBrainPlan converts an LLM-generated plan to the brain Plan type.
func generatedPlanToBrainPlan(gp *llm.GeneratedPlan, workspaceID string) *Plan {
	if gp == nil {
		return &Plan{WorkspaceID: workspaceID}
	}
	steps := make([]PlanStep, len(gp.Actions))
	for i, a := range gp.Actions {
		params := make(map[string]any, len(a.Parameters))
		for k, v := range a.Parameters {
			params[k] = v
		}
		steps[i] = PlanStep{
			ToolKey:    a.ToolKey,
			Parameters: params,
			DependsOn:  append([]int(nil), a.DependsOn...),
			Phase:      a.Phase,
		}
	}
	riskLevel := gp.RiskLevel
	if riskLevel == "" {
		riskLevel = assessRiskLevel(steps)
	}
	return &Plan{
		WorkspaceID:     workspaceID,
		Steps:           steps,
		RiskLevel:       riskLevel,
		EstimatedTokens: int(gp.Confidence * 1000),
	}
}

// generateHypotheses produces N alternative phrasings of the user's intent.
// Pure function — no I/O, no LLM calls.
func generateHypotheses(intent, memoryContext string, n int) []string {
	base := strings.TrimSpace(intent)
	if n <= 1 {
		return []string{base}
	}
	prefixes := []string{
		"",
		"The user wants to: ",
		"Interpret as a request to: ",
		"Alternative framing — ",
		"Simplified form: user needs help with ",
	}
	results := make([]string, 0, n)
	for i := 0; i < n && i < len(prefixes); i++ {
		if prefixes[i] == "" {
			results = append(results, base)
		} else {
			results = append(results, prefixes[i]+strings.ToLower(base))
		}
	}
	for len(results) < n {
		results = append(results, fmt.Sprintf("Variant %d: %s", len(results), base))
	}
	return results[:n]
}

// planWithGoT runs multi-hypothesis Graph-of-Thought planning.
// Returns nil, nil on any internal error to allow graceful fallback to standard planning.
func (rl *ReasoningLoop) planWithGoT(ctx context.Context, rc *ReasoningContext, memCtx string) (*Plan, error) {
	graph, err := rl.gotEngine.CreateGraph(rc.Intent)
	if err != nil {
		return nil, fmt.Errorf("got: CreateGraph: %w", err)
	}

	hypotheses := generateHypotheses(rc.Intent, memCtx, rl.gotBranches)

	type candidate struct {
		nodeID string
		plan   *llm.GeneratedPlan
		conf   float64
	}
	candidates := make([]candidate, 0, len(hypotheses))

	for _, hyp := range hypotheses {
		nodeID, err := rl.gotEngine.AddHypothesis(graph.ID, hyp, 0.5)
		if err != nil {
			continue
		}
		genPlan, _, err := rl.intelligence.GeneratePlan(
			ctx, hyp, rc.Confidence,
			rc.OriginalPayload, memCtx, rc.RAGContext,
		)
		if err != nil || genPlan == nil {
			_ = rl.gotEngine.Prune(graph.ID, nodeID)
			continue
		}
		candidates = append(candidates, candidate{nodeID: nodeID, plan: genPlan, conf: genPlan.Confidence})
	}

	if len(candidates) == 0 {
		return nil, fmt.Errorf("got: no valid candidates")
	}
	if len(candidates) == 1 {
		return generatedPlanToBrainPlan(candidates[0].plan, rc.WorkspaceID), nil
	}

	eval, err := rl.gotEngine.Evaluate(graph.ID)
	if err != nil || len(eval.BestPath) == 0 {
		best := candidates[0]
		for _, c := range candidates[1:] {
			if c.conf > best.conf {
				best = c
			}
		}
		return generatedPlanToBrainPlan(best.plan, rc.WorkspaceID), nil
	}

	bestNodeID := eval.BestPath[len(eval.BestPath)-1]
	for _, c := range candidates {
		if c.nodeID == bestNodeID {
			return generatedPlanToBrainPlan(c.plan, rc.WorkspaceID), nil
		}
	}

	best := candidates[0]
	for _, c := range candidates[1:] {
		if c.conf > best.conf {
			best = c
		}
	}
	return generatedPlanToBrainPlan(best.plan, rc.WorkspaceID), nil
}

// assessRiskLevel determines the overall risk of a plan based on its tool usage.
func assessRiskLevel(steps []PlanStep) string {
	highRiskTools := map[string]bool{
		"financial_write": true,
		"email_send":      true,
		"message_send":    true,
	}
	elevatedRiskTools := map[string]bool{
		"calendar_write":  true,
		"document_write":  true,
		"crm_write":       true,
	}

	risk := "low"
	for _, step := range steps {
		if highRiskTools[step.ToolKey] {
			return "critical"
		}
		if elevatedRiskTools[step.ToolKey] {
			risk = "elevated"
		}
	}
	return risk
}

// estimateTokens estimates the total token usage for a plan.
func estimateTokens(steps []PlanStep, contextBudget int) int {
	// Base cost per step + parameter overhead
	base := len(steps) * 200
	for _, step := range steps {
		base += len(step.Parameters) * 50
	}
	if contextBudget > 0 && base > contextBudget {
		return contextBudget
	}
	return base
}

// executorStepWithPRM wraps ExecutorStep and adds PRM early-termination scoring.
// Used internally by RunLoop; public ExecutorStep is preserved for tests.
func (rl *ReasoningLoop) executorStepWithPRM(ctx context.Context, plan *Plan, intent string) (*ExecutionResult, error) {
	result, err := rl.ExecutorStep(ctx, plan)
	if err != nil || result == nil || rl.prm == nil || intent == "" {
		return result, err
	}
	// PRM: check the last completed step for early termination signal.
	for i := len(result.Results) - 1; i >= 0; i-- {
		r := result.Results[i]
		if r.ToolKey == "" {
			continue
		}
		_, shouldContinue, _ := rl.prm.ScoreStep(ctx, intent, plan.Steps, result.Results, r)
		if !shouldContinue {
			// Mark remaining incomplete steps as terminated.
			for j := i + 1; j < len(result.Results); j++ {
				if !result.Results[j].Success && result.Results[j].Error == "" {
					result.Results[j].Error = fmt.Sprintf("early_termination by PRM after step %d", i)
				}
			}
			result.CompensationNeeded = true
		}
		break // only check the last meaningful step
	}
	return result, nil
}

// criticStepWithSemantic wraps CriticStep and adds semantic LLM judge when available.
// Used internally by RunLoop; public CriticStep is preserved for tests.
func (rl *ReasoningLoop) criticStepWithSemantic(ctx context.Context, plan *Plan, result *ExecutionResult, intent string) (*CriticAssessment, error) {
	// Try semantic critic first.
	if rl.semanticCritic != nil && intent != "" {
		score, err := rl.semanticCritic.Evaluate(ctx, SemanticCriticRequest{
			OriginalIntent: intent,
			Steps:          plan.Steps,
			Results:        result.Results,
		})
		if err == nil && score != nil {
			var hints []string
			if score.RetryGuidance != "" {
				hints = []string{score.RetryGuidance}
			}
			return &CriticAssessment{
				QualityScore:    score.QualityScore,
				Issues:          score.Issues,
				ShouldRetry:     score.ShouldRetry,
				RetryHints:      hints,
				SemanticVerdict: "llm_judge",
			}, nil
		}
		// Fall through to standard CriticStep on failure.
	}
	return rl.CriticStep(ctx, plan, result, intent)
}

// ExecutorStep executes plan steps respecting the dependency DAG.
// Independent steps are launched in parallel goroutines; dependent steps
// wait until all prerequisites complete successfully.
func (rl *ReasoningLoop) ExecutorStep(ctx context.Context, plan *Plan) (*ExecutionResult, error) {
	if plan == nil {
		return nil, ErrExecutorNoPlan
	}
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("reasoning: executor cancelled before start: %w", err)
	}
	if len(plan.Steps) == 0 {
		return &ExecutionResult{Results: []StepResult{}, CompensationNeeded: false}, nil
	}

	n := len(plan.Steps)
	results := make([]StepResult, n)
	completed := make([]bool, n)
	failed := make([]bool, n)
	launched := make([]bool, n)

	var mu sync.Mutex
	var wg sync.WaitGroup

	allDepsMet := func(idx int) bool {
		for _, dep := range plan.Steps[idx].DependsOn {
			if dep < 0 || dep >= n {
				return false
			}
			if !completed[dep] || failed[dep] {
				return false
			}
		}
		return true
	}

	var launchReady func()
	launchReady = func() {
		for idx := 0; idx < n; idx++ {
			if launched[idx] {
				continue
			}
			// Skip steps with a failed dependency — they will never run.
			hasFailed := false
			for _, dep := range plan.Steps[idx].DependsOn {
				if dep >= 0 && dep < n && failed[dep] {
					hasFailed = true
					break
				}
			}
			if hasFailed {
				launched[idx] = true
				completed[idx] = true
				failed[idx] = true
				results[idx] = StepResult{
					StepIndex: idx,
					ToolKey:   plan.Steps[idx].ToolKey,
					Success:   false,
					Error:     "skipped: dependency failed",
				}
				continue
			}
			if !allDepsMet(idx) {
				continue
			}
			launched[idx] = true
			wg.Add(1)
			go func(i int) {
				defer wg.Done()
				if ctxErr := ctx.Err(); ctxErr != nil {
					mu.Lock()
					results[i] = StepResult{StepIndex: i, ToolKey: plan.Steps[i].ToolKey, Success: false, Error: "context cancelled"}
					failed[i] = true
					completed[i] = true
					launchReady()
					mu.Unlock()
					return
				}
				output, err := rl.executeStep(ctx, plan.Steps[i])
				mu.Lock()
				defer mu.Unlock()
				if err != nil {
					results[i] = StepResult{StepIndex: i, ToolKey: plan.Steps[i].ToolKey, Success: false, Error: err.Error()}
					failed[i] = true
				} else {
					results[i] = StepResult{StepIndex: i, ToolKey: plan.Steps[i].ToolKey, Success: true, Output: output}
				}
				completed[i] = true
				launchReady()
			}(idx)
		}
	}

	mu.Lock()
	launchReady()
	mu.Unlock()

	wg.Wait()

	successCount := 0
	for _, r := range results {
		if r.Success {
			successCount++
		}
	}
	return &ExecutionResult{
		Results:            results,
		CompensationNeeded: successCount < n,
	}, nil
}

// executeStep runs a single step with timeout.
func (rl *ReasoningLoop) executeStep(ctx context.Context, step PlanStep) (map[string]any, error) {
	if rl.executor == nil {
		// No executor configured — return a synthetic success for planning-only mode
		return map[string]any{"status": "planned", "tool": step.ToolKey}, nil
	}

	stepCtx, cancel := context.WithTimeout(ctx, rl.stepTimeout)
	defer cancel()

	return rl.executor.Execute(stepCtx, step.ToolKey, step.Parameters)
}

// executionOrder returns step indices sorted by phase then dependency depth.
func executionOrder(steps []PlanStep) []int {
	phaseOrder := map[string]int{
		"gather": 0,
		"act":    1,
		"verify": 2,
	}

	indices := make([]int, len(steps))
	for i := range indices {
		indices[i] = i
	}

	sort.SliceStable(indices, func(a, b int) bool {
		pa := phaseOrder[steps[indices[a]].Phase]
		pb := phaseOrder[steps[indices[b]].Phase]
		if pa != pb {
			return pa < pb
		}
		// Fewer dependencies first
		return len(steps[indices[a]].DependsOn) < len(steps[indices[b]].DependsOn)
	})

	return indices
}

// CriticStep evaluates the quality of an execution result against the plan.
// When an IntelligenceService is available, it performs semantic verification
// via VerifyExecution and per-step PRM evaluation via VerifySteps. Otherwise
// it falls back to a heuristic success-ratio score.
func (rl *ReasoningLoop) CriticStep(
	ctx context.Context,
	plan *Plan,
	result *ExecutionResult,
	originalRequest string,
) (*CriticAssessment, error) {
	if plan == nil || result == nil {
		return &CriticAssessment{QualityScore: 0, ShouldRetry: true, SemanticVerdict: "heuristic"}, nil
	}

	// Heuristic base score (always computed as fallback).
	successCount := 0
	var issues []string
	for _, r := range result.Results {
		if r.Success {
			successCount++
		} else {
			issues = append(issues, fmt.Sprintf("step %d (%s) failed: %s", r.StepIndex, r.ToolKey, r.Error))
		}
	}
	if result.CompensationNeeded {
		issues = append(issues, "compensation needed for failed steps")
	}
	total := len(plan.Steps)
	if total == 0 {
		total = 1
	}
	heuristicScore := float64(successCount) / float64(total)
	assessment := &CriticAssessment{
		QualityScore:    heuristicScore,
		Issues:          issues,
		ShouldRetry:     heuristicScore < rl.qualityTarget,
		SemanticVerdict: "heuristic",
	}

	if rl.intelligence == nil {
		return assessment, nil
	}

	// Semantic evaluation via VerifyExecution.
	verifyInput := buildVerifyInput(plan, result, originalRequest)
	verifyResult, _, verifyErr := rl.intelligence.VerifyExecution(ctx, verifyInput)
	if verifyErr == nil && verifyResult != nil {
		assessment.SemanticVerdict = verifyResult.Verdict
		assessment.ShouldRetry = verifyResult.Verdict != "pass"
		if verifyResult.RetryHints != "" {
			assessment.RetryHints = append(assessment.RetryHints, verifyResult.RetryHints)
		}
		if verifyResult.Verdict == "pass" {
			assessment.QualityScore = 1.0
		} else if verifyResult.Verdict == "fail" {
			assessment.QualityScore = heuristicScore * 0.5
		}
	}

	// Per-step PRM evaluation.
	if len(result.Results) > 0 {
		inputs := make([]llm.StepEvalInput, len(result.Results))
		planDesc := fmt.Sprintf("Plan for: %s (risk: %s)", originalRequest, plan.RiskLevel)
		for i, r := range result.Results {
			phase := ""
			if i < len(plan.Steps) {
				phase = plan.Steps[i].Phase
			}
			inputs[i] = llm.StepEvalInput{
				OriginalRequest: originalRequest,
				StepIndex:       r.StepIndex,
				ToolKey:         r.ToolKey,
				Phase:           phase,
				Output:          r.Output,
				StepError:       r.Error,
				PlanContext:     planDesc,
			}
		}
		stepResults, _, prmErr := rl.intelligence.VerifySteps(ctx, inputs)
		if prmErr == nil && len(stepResults) == len(inputs) {
			verdicts := make([]StepVerdict, len(stepResults))
			var failedKeys []string
			for i, sr := range stepResults {
				verdicts[i] = StepVerdict{
					StepIndex:   inputs[i].StepIndex,
					ToolKey:     inputs[i].ToolKey,
					Verdict:     sr.Verdict,
					Explanation: sr.Explanation,
					RetryHint:   sr.RetryHint,
				}
				if sr.Verdict == "fail" {
					failedKeys = append(failedKeys, inputs[i].ToolKey)
					if sr.RetryHint != "" {
						assessment.RetryHints = append(assessment.RetryHints, sr.RetryHint)
					}
				}
			}
			assessment.StepVerdicts = verdicts
			assessment.FailedStepKeys = failedKeys
		}
	}

	return assessment, nil
}

// storeFactsFromResult extracts learnable facts from tool outputs and stores them
// in the WorldModelService for use in subsequent planning iterations.
func (rl *ReasoningLoop) storeFactsFromResult(workspaceID string, result *ExecutionResult) {
	if rl.worldModel == nil || result == nil {
		return
	}
	for _, r := range result.Results {
		if !r.Success || r.Output == nil {
			continue
		}
		var content string
		if s, ok := r.Output["summary"].(string); ok && s != "" {
			content = s
		} else if s, ok := r.Output["result"].(string); ok && s != "" {
			content = s
		} else {
			b, _ := json.Marshal(r.Output)
			content = string(b)
		}
		if len(content) > 500 {
			content = content[:500] + "..."
		}
		if content == "" {
			continue
		}
		_ = rl.worldModel.StoreFact(workspaceID, r.ToolKey, content)
	}
}

// buildVerifyInput constructs a VerifyInput from brain types for the semantic critic.
func buildVerifyInput(plan *Plan, result *ExecutionResult, originalRequest string) llm.VerifyInput {
	toolOutputs := make([]llm.ToolOutputForVerify, len(result.Results))
	for i, r := range result.Results {
		phase := ""
		if i < len(plan.Steps) {
			phase = plan.Steps[i].Phase
		}
		toolOutputs[i] = llm.ToolOutputForVerify{
			ToolKey: r.ToolKey,
			Success: r.Success,
			Phase:   phase,
		}
	}
	return llm.VerifyInput{
		OriginalRequest: originalRequest,
		Plan:            &llm.GeneratedPlan{FinalAnswerRequirements: "All plan steps must succeed and fully address: " + originalRequest},
		ToolOutputs:     toolOutputs,
	}
}

// ReflectorStep extracts lessons learned from a critic assessment to improve
// future iterations.
func (rl *ReasoningLoop) ReflectorStep(_ context.Context, assessment *CriticAssessment) (*ReflectionResult, error) {
	if assessment == nil {
		return &ReflectionResult{}, nil
	}

	var lessons []string
	var improvements []string
	confidenceAdj := 0.0

	if assessment.QualityScore >= rl.qualityTarget {
		lessons = append(lessons, "execution met quality threshold")
		confidenceAdj = 0.05
	} else {
		lessons = append(lessons, fmt.Sprintf("quality score %.2f below target %.2f", assessment.QualityScore, rl.qualityTarget))
		confidenceAdj = -0.1

		for _, issue := range assessment.Issues {
			if strings.Contains(issue, "failed") {
				lessons = append(lessons, "one or more tool calls failed — consider fallback tools")
			}
			if strings.Contains(issue, "compensation") {
				improvements = append(improvements, "add compensation/rollback steps for write operations")
			}
		}

		for _, hint := range assessment.RetryHints {
			improvements = append(improvements, hint)
		}
	}

	if assessment.QualityScore > 0 && assessment.QualityScore < 0.5 {
		improvements = append(improvements, "consider simplifying the plan to reduce failure surface")
	}

	return &ReflectionResult{
		Lessons:               deduplicate(lessons),
		ConfidenceAdjustment:  confidenceAdj,
		SuggestedImprovements: deduplicate(improvements),
	}, nil
}

// RunLoop orchestrates the full PLANNER -> EXECUTOR -> CRITIC -> REFLECTOR cycle.
// It iterates up to maxIterations times (default 3), stopping early if the critic
// score meets or exceeds the quality target (default 0.8).
func (rl *ReasoningLoop) RunLoop(ctx context.Context, rc *ReasoningContext, maxIterations int) (*LoopResult, error) {
	if rc == nil {
		return nil, ErrReasoningNoContext
	}

	// Derive effective max iterations from complexity signals.
	effectiveMax := maxIterations
	if effectiveMax <= 0 {
		effectiveMax = rl.maxIterations
	}
	if effectiveMax > rl.maxIterations {
		effectiveMax = rl.maxIterations
	}
	if rl.decomposition != nil && rc != nil {
		signals := rl.decomposition.EstimateComplexity(rc.Intent)
		dynamic := computeIterationsFromSignals(signals)
		if dynamic > effectiveMax {
			effectiveMax = dynamic
		}
	}
	if effectiveMax > rl.maxIterationsCap {
		effectiveMax = rl.maxIterationsCap
	}
	if effectiveMax < 1 {
		effectiveMax = 1
	}

	// Apply per-workspace calibrated quality target if set.
	qualityTarget := rl.qualityTarget
	if rc.WorkspaceQualityTarget > 0 && rc.WorkspaceQualityTarget <= 1.0 {
		qualityTarget = rc.WorkspaceQualityTarget
	}

	var (
		finalPlan   *Plan
		finalResult *ExecutionResult
		criticScore float64
		allLessons  []string
	)

	for i := 0; i < effectiveMax; i++ {
		if err := ctx.Err(); err != nil {
			return nil, fmt.Errorf("%w: %v", ErrReasoningTimeout, err)
		}

		// Apply context compression before each planning iteration.
		if rc.ContextBudget > 0 && rl.summarizer != nil {
			compressed, compErr := CompressConversation(
				ctx, rc.ConversationHistory, rc.ContextBudget, 6, rl.summarizer,
			)
			if compErr == nil {
				rc.ConversationHistory = compressed
			}
		}

		// On retry iterations, enrich MemoryContext with world facts learned so far.
		if i > 0 && rl.worldModel != nil {
			facts := rl.worldModel.QueryFacts(rc.WorkspaceID)
			if len(facts) > 0 {
				factStr := rl.worldModel.SerializeForContext(facts, 20)
				rc.MemoryContext = "WORLD FACTS (learned from prior tool calls):\n" +
					factStr + "\n\n" + rc.MemoryContext
			}
		}

		// 1. Plan
		plan, err := rl.PlannerStep(ctx, rc)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d planner: %w", i+1, err)
		}
		finalPlan = plan

		// 2. Execute
		result, err := rl.executorStepWithPRM(ctx, plan, rc.Intent)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d executor: %w", i+1, err)
		}
		finalResult = result
		rl.storeFactsFromResult(rc.WorkspaceID, result)

		// 3. Critique
		assessment, err := rl.criticStepWithSemantic(ctx, plan, result, rc.Intent)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d critic: %w", i+1, err)
		}
		criticScore = assessment.QualityScore

		// Feed critic retry hints into context for next planning iteration.
		if assessment != nil && len(assessment.RetryHints) > 0 {
			hints := strings.Join(assessment.RetryHints, "\n")
			if rc.RetryHints != "" {
				rc.RetryHints += "\n" + hints
			} else {
				rc.RetryHints = hints
			}
		}

		// 4. Reflect
		reflection, err := rl.ReflectorStep(ctx, assessment)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d reflector: %w", i+1, err)
		}
		allLessons = append(allLessons, reflection.Lessons...)

		// Thread retry hints from reflector into the next planning iteration (Reflexion).
		if reflection != nil && len(reflection.SuggestedImprovements) > 0 {
			hints := strings.Join(reflection.SuggestedImprovements, "\n")
			if rc.RetryHints != "" {
				rc.RetryHints += "\n" + hints
			} else {
				rc.RetryHints = hints
			}
		}

		// Adjust confidence for next iteration
		rc.Confidence += reflection.ConfidenceAdjustment
		if rc.Confidence < 0 {
			rc.Confidence = 0
		}
		if rc.Confidence > 1 {
			rc.Confidence = 1
		}

		// Stop if quality target met
		if criticScore >= qualityTarget {
			return &LoopResult{
				FinalPlan:     finalPlan,
				FinalResult:   finalResult,
				Iterations:    i + 1,
				CriticScore:   criticScore,
				Lessons:       deduplicate(allLessons),
				DynamicBudget: effectiveMax,
			}, nil
		}
	}

	return &LoopResult{
		FinalPlan:     finalPlan,
		FinalResult:   finalResult,
		Iterations:    effectiveMax,
		CriticScore:   criticScore,
		Lessons:       deduplicate(allLessons),
		DynamicBudget: effectiveMax,
	}, nil
}

// HasLLMClient reports whether an LLM client is configured.
func (rl *ReasoningLoop) HasLLMClient() bool {
	return rl.llmClient != nil
}

// computeIterationsFromSignals derives an appropriate max iteration count
// from complexity signals. Range: 1 (trivial) to 8 (very complex).
func computeIterationsFromSignals(signals ComplexitySignals) int {
	budget := 1
	if signals.IntentCount > 1 {
		budget += signals.IntentCount - 1
	}
	if signals.DomainCount > 1 {
		budget += signals.DomainCount - 1
	}
	if signals.HasDependencies {
		budget += 2
	}
	if signals.HasTemporalConstraints {
		budget += 1
	}
	if budget < 1 {
		budget = 1
	}
	if budget > 8 {
		budget = 8
	}
	return budget
}

// containsAny returns true if s contains any of the candidate substrings.
func containsAny(s string, candidates ...string) bool {
	for _, c := range candidates {
		if strings.Contains(s, c) {
			return true
		}
	}
	return false
}

// deduplicate removes duplicate strings while preserving order.
func deduplicate(items []string) []string {
	seen := make(map[string]bool, len(items))
	result := make([]string, 0, len(items))
	for _, item := range items {
		if !seen[item] {
			seen[item] = true
			result = append(result, item)
		}
	}
	return result
}

// RunReActLoop is the production reasoning path using ReAct interleaved reasoning.
func (rl *ReasoningLoop) RunReActLoop(ctx context.Context, rc *ReasoningContext) (*ReactResult, error) {
	if rl.llmClient == nil {
		return nil, fmt.Errorf("react_loop: LLMClient required")
	}
	cfg := ReactLoopConfig{
		LLMClient:      rl.llmClient,
		Executor:       rl.executor,
		Tools:          rl.registeredTools,
		MaxTurns:       reactMaxTurns,
		UseThinking:    rl.enableExtendedThinking,
		ThinkingBudget: rl.thinkingBudgetTokens,
		StepTimeout:    rl.stepTimeout,
	}
	return NewReActLoop(cfg).Run(ctx, rc)
}
