package brain

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"
)

var (
	ErrReasoningTimeout    = errors.New("reasoning: loop timed out")
	ErrReasoningNoContext  = errors.New("reasoning: no context provided")
	ErrReasoningMaxRetries = errors.New("reasoning: max iterations reached without satisfactory quality")
	ErrPlanEmpty           = errors.New("reasoning: planner produced empty plan")
	ErrExecutorNoPlan      = errors.New("reasoning: executor received nil plan")
)

// Message represents a single conversation message.
type Message struct {
	Role      string         `json:"role"`    // "user", "assistant", "system"
	Content   string         `json:"content"`
	Timestamp int64          `json:"timestamp"`
	Metadata  map[string]any `json:"metadata,omitempty"`
}

// ReasoningContext carries all context needed for a reasoning loop iteration.
type ReasoningContext struct {
	MessageID           string    `json:"message_id"`
	WorkspaceID         string    `json:"workspace_id"`
	Intent              string    `json:"intent"`
	Confidence          float64   `json:"confidence"`
	ConversationHistory []Message `json:"conversation_history"`
	ContextBudget       int       `json:"context_budget"` // max tokens to use
}

// PlanStep represents a single step in an execution plan.
type PlanStep struct {
	ToolKey    string         `json:"tool_key"`
	Parameters map[string]any `json:"parameters"`
	DependsOn  []int          `json:"depends_on,omitempty"` // indices of steps this depends on
	Phase      string         `json:"phase"`                // "gather", "act", "verify"
}

// Plan represents a complete execution plan generated by the planner.
type Plan struct {
	Steps           []PlanStep `json:"steps"`
	RiskLevel       string     `json:"risk_level"` // "low", "elevated", "critical"
	EstimatedTokens int        `json:"estimated_tokens"`
}

// StepResult captures the outcome of executing a single plan step.
type StepResult struct {
	StepIndex int            `json:"step_index"`
	ToolKey   string         `json:"tool_key"`
	Success   bool           `json:"success"`
	Output    map[string]any `json:"output,omitempty"`
	Error     string         `json:"error,omitempty"`
}

// ExecutionResult captures the outcomes of all plan steps.
type ExecutionResult struct {
	Results            []StepResult `json:"results"`
	CompensationNeeded bool         `json:"compensation_needed"`
}

// CriticAssessment evaluates the quality of an execution.
type CriticAssessment struct {
	QualityScore float64  `json:"quality_score"` // 0.0 to 1.0
	Issues       []string `json:"issues,omitempty"`
	ShouldRetry  bool     `json:"should_retry"`
	RetryHints   []string `json:"retry_hints,omitempty"`
}

// ReflectionResult captures lessons from a reasoning iteration.
type ReflectionResult struct {
	Lessons                []string `json:"lessons,omitempty"`
	ConfidenceAdjustment   float64  `json:"confidence_adjustment"` // delta to apply
	SuggestedImprovements  []string `json:"suggested_improvements,omitempty"`
}

// LoopResult is the final output of a complete reasoning loop.
type LoopResult struct {
	FinalPlan   *Plan            `json:"final_plan"`
	FinalResult *ExecutionResult `json:"final_result"`
	Iterations  int              `json:"iterations"`
	CriticScore float64          `json:"critic_score"`
	Lessons     []string         `json:"lessons,omitempty"`
}

// ToolExecutor is the interface for executing tool calls.
// Implementations bridge to the actual tool/connector layer.
type ToolExecutor interface {
	Execute(ctx context.Context, toolKey string, params map[string]any) (map[string]any, error)
}

// ReasoningLoop orchestrates the PLANNER -> EXECUTOR -> CRITIC -> REFLECTOR cycle.
type ReasoningLoop struct {
	executor       ToolExecutor
	qualityTarget  float64       // critic score threshold to stop iterating (default 0.8)
	maxIterations  int           // safety cap (default 3)
	stepTimeout    time.Duration // timeout per individual step
}

// ReasoningLoopConfig holds configuration for a ReasoningLoop.
type ReasoningLoopConfig struct {
	Executor      ToolExecutor
	QualityTarget float64
	MaxIterations int
	StepTimeout   time.Duration
}

// NewReasoningLoop creates a new ReasoningLoop with the given config.
func NewReasoningLoop(cfg ReasoningLoopConfig) *ReasoningLoop {
	qualityTarget := cfg.QualityTarget
	if qualityTarget <= 0 || qualityTarget > 1.0 {
		qualityTarget = 0.8
	}
	maxIter := cfg.MaxIterations
	if maxIter <= 0 {
		maxIter = 3
	}
	stepTimeout := cfg.StepTimeout
	if stepTimeout <= 0 {
		stepTimeout = 30 * time.Second
	}
	return &ReasoningLoop{
		executor:      cfg.Executor,
		qualityTarget: qualityTarget,
		maxIterations: maxIter,
		stepTimeout:   stepTimeout,
	}
}

// PlannerStep generates an execution plan based on the reasoning context.
// It analyzes the intent and conversation history to determine what tools
// to invoke and in what order.
func (rl *ReasoningLoop) PlannerStep(ctx context.Context, rc *ReasoningContext) (*Plan, error) {
	if rc == nil {
		return nil, ErrReasoningNoContext
	}
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("reasoning: planner cancelled: %w", err)
	}

	intent := strings.ToLower(strings.TrimSpace(rc.Intent))
	if intent == "" {
		return nil, fmt.Errorf("%w: empty intent", ErrPlanEmpty)
	}

	steps := buildStepsForIntent(intent, rc)
	if len(steps) == 0 {
		return nil, fmt.Errorf("%w: could not derive steps for intent %q", ErrPlanEmpty, rc.Intent)
	}

	riskLevel := assessRiskLevel(steps)
	estimatedTokens := estimateTokens(steps, rc.ContextBudget)

	return &Plan{
		Steps:           steps,
		RiskLevel:       riskLevel,
		EstimatedTokens: estimatedTokens,
	}, nil
}

// buildStepsForIntent derives plan steps from the intent string.
// In production this would invoke an LLM; here we use rule-based heuristics.
func buildStepsForIntent(intent string, rc *ReasoningContext) []PlanStep {
	var steps []PlanStep

	// Phase 1: Gather context
	if containsAny(intent, "email", "mail", "message") {
		steps = append(steps, PlanStep{
			ToolKey:    "email_read",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "query": rc.Intent},
			Phase:      "gather",
		})
	}
	if containsAny(intent, "calendar", "meeting", "schedule", "event") {
		steps = append(steps, PlanStep{
			ToolKey:    "calendar_read",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "query": rc.Intent},
			Phase:      "gather",
		})
	}
	if containsAny(intent, "document", "file", "doc", "note") {
		steps = append(steps, PlanStep{
			ToolKey:    "document_read",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "query": rc.Intent},
			Phase:      "gather",
		})
	}
	if containsAny(intent, "search", "find", "look up", "web") {
		steps = append(steps, PlanStep{
			ToolKey:    "web_search",
			Parameters: map[string]any{"query": rc.Intent},
			Phase:      "gather",
		})
	}

	// Phase 2: Act
	if containsAny(intent, "send", "reply", "forward") {
		gatherIdx := -1
		for i, s := range steps {
			if s.Phase == "gather" {
				gatherIdx = i
			}
		}
		step := PlanStep{
			ToolKey:    "email_send",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "intent": rc.Intent},
			Phase:      "act",
		}
		if gatherIdx >= 0 {
			step.DependsOn = []int{gatherIdx}
		}
		steps = append(steps, step)
	}
	if containsAny(intent, "create event", "schedule meeting", "book", "set up meeting") {
		step := PlanStep{
			ToolKey:    "calendar_write",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID, "intent": rc.Intent},
			Phase:      "act",
		}
		steps = append(steps, step)
	}

	// Phase 3: Verify — add a verification step if any act step exists
	hasAct := false
	for _, s := range steps {
		if s.Phase == "act" {
			hasAct = true
			break
		}
	}
	if hasAct {
		actIndices := make([]int, 0)
		for i, s := range steps {
			if s.Phase == "act" {
				actIndices = append(actIndices, i)
			}
		}
		steps = append(steps, PlanStep{
			ToolKey:    "verify_output",
			Parameters: map[string]any{"workspace_id": rc.WorkspaceID},
			DependsOn:  actIndices,
			Phase:      "verify",
		})
	}

	return steps
}

// assessRiskLevel determines the overall risk of a plan based on its tool usage.
func assessRiskLevel(steps []PlanStep) string {
	highRiskTools := map[string]bool{
		"financial_write": true,
		"email_send":      true,
		"message_send":    true,
	}
	elevatedRiskTools := map[string]bool{
		"calendar_write":  true,
		"document_write":  true,
		"crm_write":       true,
	}

	risk := "low"
	for _, step := range steps {
		if highRiskTools[step.ToolKey] {
			return "critical"
		}
		if elevatedRiskTools[step.ToolKey] {
			risk = "elevated"
		}
	}
	return risk
}

// estimateTokens estimates the total token usage for a plan.
func estimateTokens(steps []PlanStep, contextBudget int) int {
	// Base cost per step + parameter overhead
	base := len(steps) * 200
	for _, step := range steps {
		base += len(step.Parameters) * 50
	}
	if contextBudget > 0 && base > contextBudget {
		return contextBudget
	}
	return base
}

// ExecutorStep executes plan steps in dependency order, respecting the
// configured step timeout. Steps without dependencies run first; steps
// that depend on failed predecessors are skipped.
func (rl *ReasoningLoop) ExecutorStep(ctx context.Context, plan *Plan) (*ExecutionResult, error) {
	if plan == nil {
		return nil, ErrExecutorNoPlan
	}
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("reasoning: executor cancelled: %w", err)
	}

	results := make([]StepResult, len(plan.Steps))
	completed := make(map[int]bool, len(plan.Steps))
	failed := make(map[int]bool, len(plan.Steps))

	// Sort steps by phase order and dependency depth
	order := executionOrder(plan.Steps)

	for _, idx := range order {
		step := plan.Steps[idx]

		// Check if any dependency failed
		depFailed := false
		for _, dep := range step.DependsOn {
			if failed[dep] {
				depFailed = true
				break
			}
			if !completed[dep] {
				depFailed = true
				break
			}
		}

		if depFailed {
			results[idx] = StepResult{
				StepIndex: idx,
				ToolKey:   step.ToolKey,
				Success:   false,
				Error:     "dependency failed or not completed",
			}
			failed[idx] = true
			completed[idx] = true
			continue
		}

		output, err := rl.executeStep(ctx, step)
		if err != nil {
			results[idx] = StepResult{
				StepIndex: idx,
				ToolKey:   step.ToolKey,
				Success:   false,
				Error:     err.Error(),
			}
			failed[idx] = true
		} else {
			results[idx] = StepResult{
				StepIndex: idx,
				ToolKey:   step.ToolKey,
				Success:   true,
				Output:    output,
			}
		}
		completed[idx] = true
	}

	compensationNeeded := false
	for _, f := range failed {
		if f {
			compensationNeeded = true
			break
		}
	}

	return &ExecutionResult{
		Results:            results,
		CompensationNeeded: compensationNeeded,
	}, nil
}

// executeStep runs a single step with timeout.
func (rl *ReasoningLoop) executeStep(ctx context.Context, step PlanStep) (map[string]any, error) {
	if rl.executor == nil {
		// No executor configured — return a synthetic success for planning-only mode
		return map[string]any{"status": "planned", "tool": step.ToolKey}, nil
	}

	stepCtx, cancel := context.WithTimeout(ctx, rl.stepTimeout)
	defer cancel()

	return rl.executor.Execute(stepCtx, step.ToolKey, step.Parameters)
}

// executionOrder returns step indices sorted by phase then dependency depth.
func executionOrder(steps []PlanStep) []int {
	phaseOrder := map[string]int{
		"gather": 0,
		"act":    1,
		"verify": 2,
	}

	indices := make([]int, len(steps))
	for i := range indices {
		indices[i] = i
	}

	sort.SliceStable(indices, func(a, b int) bool {
		pa := phaseOrder[steps[indices[a]].Phase]
		pb := phaseOrder[steps[indices[b]].Phase]
		if pa != pb {
			return pa < pb
		}
		// Fewer dependencies first
		return len(steps[indices[a]].DependsOn) < len(steps[indices[b]].DependsOn)
	})

	return indices
}

// CriticStep evaluates the quality of an execution result against the plan.
func (rl *ReasoningLoop) CriticStep(_ context.Context, plan *Plan, result *ExecutionResult) (*CriticAssessment, error) {
	if plan == nil || result == nil {
		return &CriticAssessment{
			QualityScore: 0,
			Issues:       []string{"missing plan or result"},
			ShouldRetry:  false,
		}, nil
	}

	totalSteps := len(plan.Steps)
	if totalSteps == 0 {
		return &CriticAssessment{
			QualityScore: 0,
			Issues:       []string{"empty plan"},
			ShouldRetry:  false,
		}, nil
	}

	successCount := 0
	var issues []string
	var retryHints []string

	for _, r := range result.Results {
		if r.Success {
			successCount++
		} else {
			issues = append(issues, fmt.Sprintf("step %d (%s) failed: %s", r.StepIndex, r.ToolKey, r.Error))
			retryHints = append(retryHints, fmt.Sprintf("retry or skip step %d (%s)", r.StepIndex, r.ToolKey))
		}
	}

	score := float64(successCount) / float64(totalSteps)

	// Penalize if compensation is needed
	if result.CompensationNeeded {
		score *= 0.9
		issues = append(issues, "compensation needed for failed steps")
	}

	shouldRetry := score < rl.qualityTarget && len(retryHints) > 0

	return &CriticAssessment{
		QualityScore: score,
		Issues:       issues,
		ShouldRetry:  shouldRetry,
		RetryHints:   retryHints,
	}, nil
}

// ReflectorStep extracts lessons learned from a critic assessment to improve
// future iterations.
func (rl *ReasoningLoop) ReflectorStep(_ context.Context, assessment *CriticAssessment) (*ReflectionResult, error) {
	if assessment == nil {
		return &ReflectionResult{}, nil
	}

	var lessons []string
	var improvements []string
	confidenceAdj := 0.0

	if assessment.QualityScore >= rl.qualityTarget {
		lessons = append(lessons, "execution met quality threshold")
		confidenceAdj = 0.05
	} else {
		lessons = append(lessons, fmt.Sprintf("quality score %.2f below target %.2f", assessment.QualityScore, rl.qualityTarget))
		confidenceAdj = -0.1

		for _, issue := range assessment.Issues {
			if strings.Contains(issue, "failed") {
				lessons = append(lessons, "one or more tool calls failed — consider fallback tools")
			}
			if strings.Contains(issue, "compensation") {
				improvements = append(improvements, "add compensation/rollback steps for write operations")
			}
		}

		for _, hint := range assessment.RetryHints {
			improvements = append(improvements, hint)
		}
	}

	if assessment.QualityScore > 0 && assessment.QualityScore < 0.5 {
		improvements = append(improvements, "consider simplifying the plan to reduce failure surface")
	}

	return &ReflectionResult{
		Lessons:               deduplicate(lessons),
		ConfidenceAdjustment:  confidenceAdj,
		SuggestedImprovements: deduplicate(improvements),
	}, nil
}

// RunLoop orchestrates the full PLANNER -> EXECUTOR -> CRITIC -> REFLECTOR cycle.
// It iterates up to maxIterations times (default 3), stopping early if the critic
// score meets or exceeds the quality target (default 0.8).
func (rl *ReasoningLoop) RunLoop(ctx context.Context, rc *ReasoningContext, maxIterations int) (*LoopResult, error) {
	if rc == nil {
		return nil, ErrReasoningNoContext
	}
	if maxIterations <= 0 {
		maxIterations = rl.maxIterations
	}
	if maxIterations > rl.maxIterations {
		maxIterations = rl.maxIterations
	}

	var (
		finalPlan   *Plan
		finalResult *ExecutionResult
		criticScore float64
		allLessons  []string
	)

	for i := 0; i < maxIterations; i++ {
		if err := ctx.Err(); err != nil {
			return nil, fmt.Errorf("%w: %v", ErrReasoningTimeout, err)
		}

		// 1. Plan
		plan, err := rl.PlannerStep(ctx, rc)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d planner: %w", i+1, err)
		}
		finalPlan = plan

		// 2. Execute
		result, err := rl.ExecutorStep(ctx, plan)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d executor: %w", i+1, err)
		}
		finalResult = result

		// 3. Critique
		assessment, err := rl.CriticStep(ctx, plan, result)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d critic: %w", i+1, err)
		}
		criticScore = assessment.QualityScore

		// 4. Reflect
		reflection, err := rl.ReflectorStep(ctx, assessment)
		if err != nil {
			return nil, fmt.Errorf("reasoning: iteration %d reflector: %w", i+1, err)
		}
		allLessons = append(allLessons, reflection.Lessons...)

		// Adjust confidence for next iteration
		rc.Confidence += reflection.ConfidenceAdjustment
		if rc.Confidence < 0 {
			rc.Confidence = 0
		}
		if rc.Confidence > 1 {
			rc.Confidence = 1
		}

		// Stop if quality target met
		if criticScore >= rl.qualityTarget {
			return &LoopResult{
				FinalPlan:   finalPlan,
				FinalResult: finalResult,
				Iterations:  i + 1,
				CriticScore: criticScore,
				Lessons:     deduplicate(allLessons),
			}, nil
		}
	}

	return &LoopResult{
		FinalPlan:   finalPlan,
		FinalResult: finalResult,
		Iterations:  maxIterations,
		CriticScore: criticScore,
		Lessons:     deduplicate(allLessons),
	}, nil
}

// containsAny returns true if s contains any of the candidate substrings.
func containsAny(s string, candidates ...string) bool {
	for _, c := range candidates {
		if strings.Contains(s, c) {
			return true
		}
	}
	return false
}

// deduplicate removes duplicate strings while preserving order.
func deduplicate(items []string) []string {
	seen := make(map[string]bool, len(items))
	result := make([]string, 0, len(items))
	for _, item := range items {
		if !seen[item] {
			seen[item] = true
			result = append(result, item)
		}
	}
	return result
}
