package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type connectorSeedFile struct {
	Connectors []connectorSeed `yaml:"connectors"`
}

type connectorSeed struct {
	Key          string `yaml:"key"`
	Domain       string `yaml:"domain"`
	RiskLevel    string `yaml:"risk_level"`
	DataClass    string `yaml:"data_class"`
	MCPServerURL string `yaml:"mcp_server_url"`
}

type mcpBudgetPolicy struct {
	MonthlyCallCap     int
	MonthlyCostCapUSD  float64
	RateLimitPerMinute int
}

func main() {
	root, err := repoRoot()
	if err != nil {
		fail(err)
	}

	seedsPath := filepath.Join(root, "internal", "connectors", "seeds", "connectors.yaml")
	raw, err := os.ReadFile(seedsPath)
	if err != nil {
		fail(err)
	}

	var seeds connectorSeedFile
	if err := yaml.Unmarshal(raw, &seeds); err != nil {
		fail(fmt.Errorf("parse connectors seed file: %w", err))
	}
	if len(seeds.Connectors) == 0 {
		fail(fmt.Errorf("no connectors found in %s", seedsPath))
	}

	connectedSet := parseConnectedSet(os.Getenv("CONNECTED_CONNECTOR_KEYS"))
	connected := make([]connectorSeed, 0, len(seeds.Connectors))
	available := make([]connectorSeed, 0, len(seeds.Connectors))
	for _, connector := range seeds.Connectors {
		if _, ok := connectedSet[connector.Key]; ok {
			connected = append(connected, connector)
			continue
		}
		available = append(available, connector)
	}

	sort.Slice(connected, func(i, j int) bool { return connected[i].Key < connected[j].Key })
	sort.Slice(available, func(i, j int) bool { return available[i].Key < available[j].Key })

	outPath := filepath.Join(root, "TOOLS.md")
	var buffer bytes.Buffer
	buffer.WriteString("# TOOLS\n\n")
	buffer.WriteString("Generated by `scripts/tools/generate_tools_md.go`.\n\n")
	buffer.WriteString("This catalog is generated from `internal/connectors/seeds/connectors.yaml`.\n\n")

	buffer.WriteString("## Connected Apps\n\n")
	if len(connected) == 0 {
		buffer.WriteString("_No connectors marked as connected. Set `CONNECTED_CONNECTOR_KEYS` (comma-separated) before generation._\n\n")
	} else {
		writeConnectorTable(&buffer, connected)
	}

	buffer.WriteString("## Available But Not Connected\n\n")
	writeConnectorTable(&buffer, available)

	buffer.WriteString("## MCP Budget And Rate-Limit Matrix\n\n")
	writeMCPBudgetTable(&buffer, seeds.Connectors)

	buffer.WriteString("## Budget And Usage Signals\n\n")
	buffer.WriteString("- Enforce per-workspace rate limits and monthly budgets before write operations.\n")
	buffer.WriteString("- Track per-call usage in `tool_executions` and aggregate metrics in observability pipelines.\n")
	buffer.WriteString("- Meter MCP server usage via `internal/mcp` invocation ledger and enforce server policy gates before execution.\n")
	buffer.WriteString("- Surface MCP usage/cost in admin (`/v1/admin/operations/dashboard`, `/v1/admin/costs/summary`) and TOOLS catalog.\n")
	buffer.WriteString("- Review high-risk connectors (`risk_level=CRITICAL`) for explicit approval requirements.\n")

	if err := os.WriteFile(outPath, buffer.Bytes(), 0o644); err != nil {
		fail(err)
	}

	fmt.Printf("generated %s with %d connected and %d available connectors\n", outPath, len(connected), len(available))
}

func writeConnectorTable(buffer *bytes.Buffer, connectors []connectorSeed) {
	buffer.WriteString("| connector_key | domain | risk_level | data_class | mcp_server_url |\n")
	buffer.WriteString("|---|---|---|---|---|\n")
	for _, connector := range connectors {
		buffer.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
			connector.Key,
			connector.Domain,
			connector.RiskLevel,
			connector.DataClass,
			connector.MCPServerURL,
		))
	}
	buffer.WriteString("\n")
}

func writeMCPBudgetTable(buffer *bytes.Buffer, connectors []connectorSeed) {
	sorted := make([]connectorSeed, len(connectors))
	copy(sorted, connectors)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Key < sorted[j].Key
	})

	buffer.WriteString("| connector_key | risk_level | monthly_call_cap | monthly_cost_cap_usd | rate_limit_per_minute | metering_source |\n")
	buffer.WriteString("|---|---|---:|---:|---:|---|\n")
	for _, connector := range sorted {
		policy := budgetPolicyForRisk(connector.RiskLevel)
		buffer.WriteString(fmt.Sprintf("| %s | %s | %d | %.2f | %d | %s |\n",
			connector.Key,
			connector.RiskLevel,
			policy.MonthlyCallCap,
			policy.MonthlyCostCapUSD,
			policy.RateLimitPerMinute,
			"`tool_executions` + mcp invocation ledger",
		))
	}
	buffer.WriteString("\n")
}

func budgetPolicyForRisk(riskLevel string) mcpBudgetPolicy {
	switch strings.ToUpper(strings.TrimSpace(riskLevel)) {
	case "CRITICAL":
		return mcpBudgetPolicy{MonthlyCallCap: 1000, MonthlyCostCapUSD: 200.00, RateLimitPerMinute: 30}
	case "ELEVATED":
		return mcpBudgetPolicy{MonthlyCallCap: 1500, MonthlyCostCapUSD: 120.00, RateLimitPerMinute: 60}
	case "MEDIUM":
		return mcpBudgetPolicy{MonthlyCallCap: 2000, MonthlyCostCapUSD: 80.00, RateLimitPerMinute: 90}
	default:
		return mcpBudgetPolicy{MonthlyCallCap: 5000, MonthlyCostCapUSD: 40.00, RateLimitPerMinute: 120}
	}
}

func parseConnectedSet(value string) map[string]struct{} {
	out := map[string]struct{}{}
	for _, part := range strings.Split(value, ",") {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		out[trimmed] = struct{}{}
	}
	return out
}

func repoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return cwd, nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
