from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from sqlalchemy.orm import Session

from app.blueprint.knowledge_files import get_latest_knowledge_file, put_knowledge_file_version
from app.blueprint.mcp.registry import MCPServerRegistry
from app.blueprint.tools import get_tool_registry
from app.services.provisioning_catalog import available_servers_for_user, render_available_servers_section


_SKIP_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    "storage",
}


def _discover_service_modules(repo_root: Path) -> list[str]:
    services_dir = repo_root / "app" / "services"
    if not services_dir.exists():
        return []
    out: list[str] = []
    for item in sorted(services_dir.glob("*.py")):
        if item.name.startswith("_") or item.name == "__init__.py":
            continue
        out.append(f"app.services.{item.stem}")
    return out


def _discover_skill_files(repo_root: Path) -> list[str]:
    out: list[str] = []
    for path in repo_root.rglob("SKILL.md"):
        rel_parts = path.relative_to(repo_root).parts
        if any(part in _SKIP_DIRS for part in rel_parts):
            continue
        out.append(str(path.relative_to(repo_root)))
    return sorted(set(out))


def _tools_catalog_markdown(
    *,
    native_tools: list[dict[str, Any]],
    mcp_servers: list[dict[str, Any]],
    available_servers: list[dict[str, Any]],
    services: list[str],
    skills: list[str],
) -> str:
    lines = [
        "# TOOLS.md",
        f"_Generated by Bones scan at {datetime.utcnow().isoformat()}_",
        "",
        "## Native Tool Registry",
    ]
    if native_tools:
        for item in native_tools:
            lines.append(
                f"- {item['name']} | risk={item['risk']} | mcp={item['is_mcp']} | tags={', '.join(item['tags']) or '-'}"
            )
    else:
        lines.append("- No tools registered.")

    lines.extend(["", "## MCP Catalog"])
    if mcp_servers:
        for server in mcp_servers:
            lines.append(
                f"- {server.get('display_name') or server.get('server_id')} "
                f"({server.get('server_id')}) | state={server.get('state')} | tools={server.get('tools_count', 0)}"
            )
    else:
        lines.append("- No MCP servers bound.")

    lines.extend(["", render_available_servers_section(available_servers)])

    lines.extend(["", "## Service Modules (Repository Scan)"])
    if services:
        for name in services:
            lines.append(f"- {name}")
    else:
        lines.append("- No service modules discovered.")

    lines.extend(["", "## Skill Files (Repository Scan)"])
    if skills:
        for path in skills:
            lines.append(f"- {path}")
    else:
        lines.append("- No SKILL.md files discovered in repository.")
    return "\n".join(lines).strip()


def refresh_bones_catalog(
    db: Session,
    *,
    user_id: str,
    repo_root: str | None = None,
) -> dict[str, Any]:
    root = Path(repo_root).resolve() if repo_root else Path.cwd().resolve()

    registry = get_tool_registry()
    tool_specs = registry.list_for_context(tier=99)
    native_tools = [
        {
            "name": spec.name,
            "risk": spec.risk_level.value,
            "is_mcp": bool(spec.is_mcp),
            "tags": list(spec.tags or []),
        }
        for spec in sorted(tool_specs, key=lambda s: s.name)
    ]

    mcp_registry = MCPServerRegistry()
    mcp_registry.ensure_tables(db)
    mcp_servers = [item.model_dump() for item in mcp_registry.list_servers(db, user_id=user_id)]
    connected_ids = {
        str(item.get("server_id") or "").strip()
        for item in mcp_servers
        if str(item.get("server_id") or "").strip()
    }
    available_servers = available_servers_for_user(
        db,
        user_id=user_id,
        connected_server_ids=connected_ids,
    )

    services = _discover_service_modules(root)
    skills = _discover_skill_files(root)
    content = _tools_catalog_markdown(
        native_tools=native_tools,
        mcp_servers=mcp_servers,
        available_servers=available_servers,
        services=services,
        skills=skills,
    )

    latest = get_latest_knowledge_file(db, user_id=user_id, file_path="TOOLS.md")
    changed = str((latest or {}).get("content") or "").strip() != content.strip()
    if changed:
        put_knowledge_file_version(
            db,
            user_id=user_id,
            file_path="TOOLS.md",
            content=content,
            metadata={
                "source": "bones_scan",
                "native_tool_count": len(native_tools),
                "mcp_server_count": len(mcp_servers),
                "available_server_count": len(available_servers),
                "service_module_count": len(services),
                "skill_count": len(skills),
            },
        )

    return {
        "ok": True,
        "changed": changed,
        "native_tool_count": len(native_tools),
        "mcp_server_count": len(mcp_servers),
        "service_module_count": len(services),
        "skill_count": len(skills),
    }
