// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/hands/v1/hands.proto

package handsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSkillsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId      string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	FilterCategories []string               `protobuf:"bytes,2,rep,name=filter_categories,json=filterCategories,proto3" json:"filter_categories,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_proto_hands_v1_hands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hands_v1_hands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hands_v1_hands_proto_rawDescGZIP(), []int{0}
}

func (x *ListSkillsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListSkillsRequest) GetFilterCategories() []string {
	if x != nil {
		return x.FilterCategories
	}
	return nil
}

type SkillDescriptor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SkillId        string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	RequiredScopes []string               `protobuf:"bytes,5,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	IsEnabled      bool                   `protobuf:"varint,6,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	Plane          string                 `protobuf:"bytes,7,opt,name=plane,proto3" json:"plane,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SkillDescriptor) Reset() {
	*x = SkillDescriptor{}
	mi := &file_proto_hands_v1_hands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillDescriptor) ProtoMessage() {}

func (x *SkillDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hands_v1_hands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillDescriptor.ProtoReflect.Descriptor instead.
func (*SkillDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_hands_v1_hands_proto_rawDescGZIP(), []int{1}
}

func (x *SkillDescriptor) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillDescriptor) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SkillDescriptor) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

func (x *SkillDescriptor) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *SkillDescriptor) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*SkillDescriptor     `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_proto_hands_v1_hands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hands_v1_hands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hands_v1_hands_proto_rawDescGZIP(), []int{2}
}

func (x *ListSkillsResponse) GetSkills() []*SkillDescriptor {
	if x != nil {
		return x.Skills
	}
	return nil
}

type ExecuteSkillRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId    string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SkillId        string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	InputJson      string                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	OauthToken     string                 `protobuf:"bytes,4,opt,name=oauth_token,json=oauthToken,proto3" json:"oauth_token,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteSkillRequest) Reset() {
	*x = ExecuteSkillRequest{}
	mi := &file_proto_hands_v1_hands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSkillRequest) ProtoMessage() {}

func (x *ExecuteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hands_v1_hands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSkillRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSkillRequest) Descriptor() ([]byte, []int) {
	return file_proto_hands_v1_hands_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteSkillRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ExecuteSkillRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *ExecuteSkillRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ExecuteSkillRequest) GetOauthToken() string {
	if x != nil {
		return x.OauthToken
	}
	return ""
}

func (x *ExecuteSkillRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteSkillRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecuteSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OutputJson    string                 `protobuf:"bytes,2,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSkillResponse) Reset() {
	*x = ExecuteSkillResponse{}
	mi := &file_proto_hands_v1_hands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSkillResponse) ProtoMessage() {}

func (x *ExecuteSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hands_v1_hands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSkillResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSkillResponse) Descriptor() ([]byte, []int) {
	return file_proto_hands_v1_hands_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteSkillResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ExecuteSkillResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecuteSkillResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ExecuteSkillResponse) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

type CheckSkillHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSkillHealthRequest) Reset() {
	*x = CheckSkillHealthRequest{}
	mi := &file_proto_hands_v1_hands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSkillHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSkillHealthRequest) ProtoMessage() {}

func (x *CheckSkillHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hands_v1_hands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSkillHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckSkillHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_hands_v1_hands_proto_rawDescGZIP(), []int{5}
}

func (x *CheckSkillHealthRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type CheckSkillHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSkillHealthResponse) Reset() {
	*x = CheckSkillHealthResponse{}
	mi := &file_proto_hands_v1_hands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSkillHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSkillHealthResponse) ProtoMessage() {}

func (x *CheckSkillHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hands_v1_hands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSkillHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckSkillHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_hands_v1_hands_proto_rawDescGZIP(), []int{6}
}

func (x *CheckSkillHealthResponse) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *CheckSkillHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckSkillHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_hands_v1_hands_proto protoreflect.FileDescriptor

const file_proto_hands_v1_hands_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/hands/v1/hands.proto\x12\bhands.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x11ListSkillsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12+\n" +
	"\x11filter_categories\x18\x02 \x03(\tR\x10filterCategories\"\xdc\x01\n" +
	"\x0fSkillDescriptor\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12'\n" +
	"\x0frequired_scopes\x18\x05 \x03(\tR\x0erequiredScopes\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x06 \x01(\bR\tisEnabled\x12\x14\n" +
	"\x05plane\x18\a \x01(\tR\x05plane\"G\n" +
	"\x12ListSkillsResponse\x121\n" +
	"\x06skills\x18\x01 \x03(\v2\x19.hands.v1.SkillDescriptorR\x06skills\"\xe5\x01\n" +
	"\x13ExecuteSkillRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\x12\x1f\n" +
	"\voauth_token\x18\x04 \x01(\tR\n" +
	"oauthToken\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\"\xd2\x01\n" +
	"\x14ExecuteSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\voutput_json\x18\x02 \x01(\tR\n" +
	"outputJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12;\n" +
	"\vexecuted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\"4\n" +
	"\x17CheckSkillHealthRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\"g\n" +
	"\x18CheckSkillHealthResponse\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x81\x02\n" +
	"\fHandsService\x12G\n" +
	"\n" +
	"ListSkills\x12\x1b.hands.v1.ListSkillsRequest\x1a\x1c.hands.v1.ListSkillsResponse\x12M\n" +
	"\fExecuteSkill\x12\x1d.hands.v1.ExecuteSkillRequest\x1a\x1e.hands.v1.ExecuteSkillResponse\x12Y\n" +
	"\x10CheckSkillHealth\x12!.hands.v1.CheckSkillHealthRequest\x1a\".hands.v1.CheckSkillHealthResponseB1Z/github.com/brevio/brevio/proto/hands/v1;handsv1b\x06proto3"

var (
	file_proto_hands_v1_hands_proto_rawDescOnce sync.Once
	file_proto_hands_v1_hands_proto_rawDescData []byte
)

func file_proto_hands_v1_hands_proto_rawDescGZIP() []byte {
	file_proto_hands_v1_hands_proto_rawDescOnce.Do(func() {
		file_proto_hands_v1_hands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hands_v1_hands_proto_rawDesc), len(file_proto_hands_v1_hands_proto_rawDesc)))
	})
	return file_proto_hands_v1_hands_proto_rawDescData
}

var file_proto_hands_v1_hands_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_hands_v1_hands_proto_goTypes = []any{
	(*ListSkillsRequest)(nil),        // 0: hands.v1.ListSkillsRequest
	(*SkillDescriptor)(nil),          // 1: hands.v1.SkillDescriptor
	(*ListSkillsResponse)(nil),       // 2: hands.v1.ListSkillsResponse
	(*ExecuteSkillRequest)(nil),      // 3: hands.v1.ExecuteSkillRequest
	(*ExecuteSkillResponse)(nil),     // 4: hands.v1.ExecuteSkillResponse
	(*CheckSkillHealthRequest)(nil),  // 5: hands.v1.CheckSkillHealthRequest
	(*CheckSkillHealthResponse)(nil), // 6: hands.v1.CheckSkillHealthResponse
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_proto_hands_v1_hands_proto_depIdxs = []int32{
	1, // 0: hands.v1.ListSkillsResponse.skills:type_name -> hands.v1.SkillDescriptor
	7, // 1: hands.v1.ExecuteSkillResponse.executed_at:type_name -> google.protobuf.Timestamp
	0, // 2: hands.v1.HandsService.ListSkills:input_type -> hands.v1.ListSkillsRequest
	3, // 3: hands.v1.HandsService.ExecuteSkill:input_type -> hands.v1.ExecuteSkillRequest
	5, // 4: hands.v1.HandsService.CheckSkillHealth:input_type -> hands.v1.CheckSkillHealthRequest
	2, // 5: hands.v1.HandsService.ListSkills:output_type -> hands.v1.ListSkillsResponse
	4, // 6: hands.v1.HandsService.ExecuteSkill:output_type -> hands.v1.ExecuteSkillResponse
	6, // 7: hands.v1.HandsService.CheckSkillHealth:output_type -> hands.v1.CheckSkillHealthResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_hands_v1_hands_proto_init() }
func file_proto_hands_v1_hands_proto_init() {
	if File_proto_hands_v1_hands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hands_v1_hands_proto_rawDesc), len(file_proto_hands_v1_hands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hands_v1_hands_proto_goTypes,
		DependencyIndexes: file_proto_hands_v1_hands_proto_depIdxs,
		MessageInfos:      file_proto_hands_v1_hands_proto_msgTypes,
	}.Build()
	File_proto_hands_v1_hands_proto = out.File
	file_proto_hands_v1_hands_proto_goTypes = nil
	file_proto_hands_v1_hands_proto_depIdxs = nil
}
