// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/hands/v1/hands.proto

package handsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandsService_ListSkills_FullMethodName       = "/hands.v1.HandsService/ListSkills"
	HandsService_ExecuteSkill_FullMethodName     = "/hands.v1.HandsService/ExecuteSkill"
	HandsService_CheckSkillHealth_FullMethodName = "/hands.v1.HandsService/CheckSkillHealth"
)

// HandsServiceClient is the client API for HandsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandsServiceClient interface {
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	ExecuteSkill(ctx context.Context, in *ExecuteSkillRequest, opts ...grpc.CallOption) (*ExecuteSkillResponse, error)
	CheckSkillHealth(ctx context.Context, in *CheckSkillHealthRequest, opts ...grpc.CallOption) (*CheckSkillHealthResponse, error)
}

type handsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandsServiceClient(cc grpc.ClientConnInterface) HandsServiceClient {
	return &handsServiceClient{cc}
}

func (c *handsServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, HandsService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handsServiceClient) ExecuteSkill(ctx context.Context, in *ExecuteSkillRequest, opts ...grpc.CallOption) (*ExecuteSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSkillResponse)
	err := c.cc.Invoke(ctx, HandsService_ExecuteSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handsServiceClient) CheckSkillHealth(ctx context.Context, in *CheckSkillHealthRequest, opts ...grpc.CallOption) (*CheckSkillHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSkillHealthResponse)
	err := c.cc.Invoke(ctx, HandsService_CheckSkillHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandsServiceServer is the server API for HandsService service.
// All implementations must embed UnimplementedHandsServiceServer
// for forward compatibility.
type HandsServiceServer interface {
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	ExecuteSkill(context.Context, *ExecuteSkillRequest) (*ExecuteSkillResponse, error)
	CheckSkillHealth(context.Context, *CheckSkillHealthRequest) (*CheckSkillHealthResponse, error)
	mustEmbedUnimplementedHandsServiceServer()
}

// UnimplementedHandsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandsServiceServer struct{}

func (UnimplementedHandsServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedHandsServiceServer) ExecuteSkill(context.Context, *ExecuteSkillRequest) (*ExecuteSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSkill not implemented")
}
func (UnimplementedHandsServiceServer) CheckSkillHealth(context.Context, *CheckSkillHealthRequest) (*CheckSkillHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSkillHealth not implemented")
}
func (UnimplementedHandsServiceServer) mustEmbedUnimplementedHandsServiceServer() {}
func (UnimplementedHandsServiceServer) testEmbeddedByValue()                      {}

// UnsafeHandsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandsServiceServer will
// result in compilation errors.
type UnsafeHandsServiceServer interface {
	mustEmbedUnimplementedHandsServiceServer()
}

func RegisterHandsServiceServer(s grpc.ServiceRegistrar, srv HandsServiceServer) {
	// If the following call panics, it indicates UnimplementedHandsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandsService_ServiceDesc, srv)
}

func _HandsService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandsServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandsService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandsServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandsService_ExecuteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandsServiceServer).ExecuteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandsService_ExecuteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandsServiceServer).ExecuteSkill(ctx, req.(*ExecuteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandsService_CheckSkillHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSkillHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandsServiceServer).CheckSkillHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandsService_CheckSkillHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandsServiceServer).CheckSkillHealth(ctx, req.(*CheckSkillHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandsService_ServiceDesc is the grpc.ServiceDesc for HandsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hands.v1.HandsService",
	HandlerType: (*HandsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSkills",
			Handler:    _HandsService_ListSkills_Handler,
		},
		{
			MethodName: "ExecuteSkill",
			Handler:    _HandsService_ExecuteSkill_Handler,
		},
		{
			MethodName: "CheckSkillHealth",
			Handler:    _HandsService_CheckSkillHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hands/v1/hands.proto",
}
