service:
  type: ClusterIP
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:105914556507:certificate/c3f3b7e4-7c6e-4020-bae3-7f173b89ae6e
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/live
    external-dns.alpha.kubernetes.io/hostname: api.testing-orbit.com
  hosts:
    - host: api.testing-orbit.com
      paths:
        - path: /
          pathType: Prefix
