replicaCount: 2
image:
  repository: ghcr.io/brevio/admin-frontend
  tag: v9.2.0
service:
  type: ClusterIP
  port: 8080
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 2
resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: admin.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
