replicaCount: 2
image:
  repository: ghcr.io/brevio/admin-frontend
  tag: v9.2.0
service:
  port: 8080
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 2
resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
